-- Owner-authorized removal of the eight original fictional identities.
-- Official website records, API connections and sourced offers are excluded.
-- Service, price and sync foreign keys cascade; audit history is retained.
INSERT INTO audit_entries (action, entityType, entityId, summary, metadata) SELECT 'marketplace.demo.remove', 'provider', CAST(p.id AS CHAR), 'Removed an original fictional provider at the owner request', JSON_OBJECT('slug',p.slug,'name',p.name,'servicesRemoved',(SELECT COUNT(*) FROM service_records s WHERE s.providerId=p.id),'reason','Production catalogue must contain real provider records only') FROM provider_records p WHERE p.slug IN ('northstar-social','pulse-media-lab','sociaflow','apex-smm','hyperviral-cloud','peak-engagement','smmboost-pro','orbit-reach') AND p.websiteUrl IS NULL AND NOT EXISTS (SELECT 1 FROM provider_integrations i WHERE i.providerId = p.id) AND NOT EXISTS (SELECT 1 FROM service_records s WHERE s.providerId = p.id AND s.sourceKind IN ('provider_api','public_web'));
--> statement-breakpoint
DELETE l FROM localized_content l JOIN service_records s ON l.entityId IN (CAST(s.id AS CHAR), CONCAT('service-',s.id)) JOIN provider_records p ON p.id=s.providerId WHERE l.entityType='service' AND p.slug IN ('northstar-social','pulse-media-lab','sociaflow','apex-smm','hyperviral-cloud','peak-engagement','smmboost-pro','orbit-reach') AND p.websiteUrl IS NULL AND NOT EXISTS (SELECT 1 FROM provider_integrations i WHERE i.providerId = p.id) AND NOT EXISTS (SELECT 1 FROM service_records s WHERE s.providerId = p.id AND s.sourceKind IN ('provider_api','public_web'));
--> statement-breakpoint
DELETE l FROM localized_content l JOIN provider_records p ON l.entityId IN (CAST(p.id AS CHAR), CONCAT('provider-',p.id)) WHERE l.entityType='provider' AND p.slug IN ('northstar-social','pulse-media-lab','sociaflow','apex-smm','hyperviral-cloud','peak-engagement','smmboost-pro','orbit-reach') AND p.websiteUrl IS NULL AND NOT EXISTS (SELECT 1 FROM provider_integrations i WHERE i.providerId = p.id) AND NOT EXISTS (SELECT 1 FROM service_records s WHERE s.providerId = p.id AND s.sourceKind IN ('provider_api','public_web'));
--> statement-breakpoint
DELETE p FROM provider_records p WHERE p.slug IN ('northstar-social','pulse-media-lab','sociaflow','apex-smm','hyperviral-cloud','peak-engagement','smmboost-pro','orbit-reach') AND p.websiteUrl IS NULL AND NOT EXISTS (SELECT 1 FROM provider_integrations i WHERE i.providerId = p.id) AND NOT EXISTS (SELECT 1 FROM service_records s WHERE s.providerId = p.id AND s.sourceKind IN ('provider_api','public_web'));
