-- Owner-authorized correction: publish the existing API connection, not manually researched listings.
ALTER TABLE provider_records ADD COLUMN apiCataloguePublished boolean NOT NULL DEFAULT false;
--> statement-breakpoint
INSERT INTO audit_entries (action,entityType,entityId,summary,metadata) SELECT 'marketplace.manual.remove','provider',CAST(p.id AS CHAR),'Owner requested removal of manually added providers; retain connected API providers',JSON_OBJECT('name',p.name,'slug',p.slug,'servicesRemoved',(SELECT COUNT(*) FROM service_records s WHERE s.providerId=p.id)) FROM provider_records p WHERE p.name IN ('Follow.sale','SMMPakPanel','SMM Africa','$99 Social','LYFE Marketing','WebFX') AND NOT EXISTS (SELECT 1 FROM provider_integrations i WHERE i.providerId=p.id) AND NOT EXISTS (SELECT 1 FROM service_records s WHERE s.providerId=p.id AND s.sourceKind='provider_api');
--> statement-breakpoint
DELETE l FROM localized_content l JOIN service_records s ON CAST(l.entityId AS BINARY) IN (CAST(s.id AS BINARY),CAST(CONCAT('service-',s.id) AS BINARY)) JOIN provider_records p ON p.id=s.providerId WHERE l.entityType='service' AND p.name IN ('Follow.sale','SMMPakPanel','SMM Africa','$99 Social','LYFE Marketing','WebFX') AND NOT EXISTS (SELECT 1 FROM provider_integrations i WHERE i.providerId=p.id) AND NOT EXISTS (SELECT 1 FROM service_records s WHERE s.providerId=p.id AND s.sourceKind='provider_api');
--> statement-breakpoint
DELETE l FROM localized_content l JOIN provider_records p ON CAST(l.entityId AS BINARY) IN (CAST(p.id AS BINARY),CAST(CONCAT('provider-',p.id) AS BINARY)) WHERE l.entityType='provider' AND p.name IN ('Follow.sale','SMMPakPanel','SMM Africa','$99 Social','LYFE Marketing','WebFX') AND NOT EXISTS (SELECT 1 FROM provider_integrations i WHERE i.providerId=p.id) AND NOT EXISTS (SELECT 1 FROM service_records s WHERE s.providerId=p.id AND s.sourceKind='provider_api');
--> statement-breakpoint
DELETE p FROM provider_records p WHERE p.name IN ('Follow.sale','SMMPakPanel','SMM Africa','$99 Social','LYFE Marketing','WebFX') AND NOT EXISTS (SELECT 1 FROM provider_integrations i WHERE i.providerId=p.id) AND NOT EXISTS (SELECT 1 FROM service_records s WHERE s.providerId=p.id AND s.sourceKind='provider_api');
--> statement-breakpoint
INSERT INTO audit_entries (action,entityType,entityId,summary,metadata) SELECT 'provider.api_catalogue.publish','provider',CAST(p.id AS CHAR),'Owner requested publication of the connected JustAnotherPanel source catalogue',JSON_OBJECT('mode','api_source','previousStatus',p.status,'qualityVerified',false,'serviceReviewsUnchanged',true) FROM provider_records p WHERE p.slug='justanotherpanel' AND p.status <> 'suspended' AND p.apiCataloguePublished=false AND EXISTS (SELECT 1 FROM provider_integrations i WHERE i.providerId=p.id AND i.baseUrl='https://justanotherpanel.com/api/v2' AND i.status='active' AND i.lastSyncedAt IS NOT NULL AND i.credentialCiphertext IS NOT NULL);
--> statement-breakpoint
UPDATE provider_records p SET p.status='active',p.apiCataloguePublished=true WHERE p.slug='justanotherpanel' AND p.status <> 'suspended' AND EXISTS (SELECT 1 FROM provider_integrations i WHERE i.providerId=p.id AND i.baseUrl='https://justanotherpanel.com/api/v2' AND i.status='active' AND i.lastSyncedAt IS NOT NULL AND i.credentialCiphertext IS NOT NULL);
