import { boolean, decimal, index, int, json, mysqlEnum, mysqlTable, primaryKey, text, timestamp, uniqueIndex, varchar } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export const staffAccounts = mysqlTable("staff_accounts", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull().references(() => users.id, { onDelete: "cascade" }),
  email: varchar("email", { length: 320 }).notNull(),
  passwordHash: varchar("passwordHash", { length: 255 }).notNull(),
  passwordChangedAt: timestamp("passwordChangedAt").defaultNow().notNull(),
  failedLoginAttempts: int("failedLoginAttempts").default(0).notNull(),
  lockedUntil: timestamp("lockedUntil"),
  mfaEnabled: boolean("mfaEnabled").default(false).notNull(),
  mfaSecretCiphertext: text("mfaSecretCiphertext"),
  mfaSecretIv: varchar("mfaSecretIv", { length: 64 }),
  mfaSecretTag: varchar("mfaSecretTag", { length: 64 }),
  mfaSecretVersion: int("mfaSecretVersion").default(1).notNull(),
  recoveryCodeHashes: json("recoveryCodeHashes").$type<string[]>(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
}, table => [uniqueIndex("staff_account_user_unique").on(table.userId), uniqueIndex("staff_account_email_unique").on(table.email)]);

export const staffSessions = mysqlTable("staff_sessions", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull().references(() => users.id, { onDelete: "cascade" }),
  tokenHash: varchar("tokenHash", { length: 64 }).notNull(),
  mfaVerified: boolean("mfaVerified").default(false).notNull(),
  ipAddress: varchar("ipAddress", { length: 64 }),
  userAgent: varchar("userAgent", { length: 500 }),
  expiresAt: timestamp("expiresAt").notNull(),
  lastSeenAt: timestamp("lastSeenAt").defaultNow().notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
}, table => [uniqueIndex("staff_session_token_unique").on(table.tokenHash), index("staff_session_user_expiry_idx").on(table.userId, table.expiresAt)]);

export const providerRecords = mysqlTable("provider_records", {
  id: int("id").autoincrement().primaryKey(),
  slug: varchar("slug", { length: 160 }).notNull(),
  name: varchar("name", { length: 200 }).notNull(),
  initials: varchar("initials", { length: 12 }).notNull(),
  status: mysqlEnum("status", ["draft", "pending_review", "active", "suspended"]).default("draft").notNull(),
  tier: mysqlEnum("tier", ["tier_1_direct", "verified_enterprise", "certified_wholesale", "specialized_partner"]).default("specialized_partner").notNull(),
  countryCode: varchar("countryCode", { length: 2 }),
  location: varchar("location", { length: 160 }),
  description: text("description"),
  websiteUrl: varchar("websiteUrl", { length: 500 }),
  verified: boolean("verified").default(false).notNull(),
  score: int("score").default(0).notNull(),
  ratingBasisPoints: int("ratingBasisPoints").default(0).notNull(),
  reviewCount: int("reviewCount").default(0).notNull(),
  responseMinutes: int("responseMinutes"),
  apiLatencyMs: int("apiLatencyMs"),
  apiUptimeBasisPoints: int("apiUptimeBasisPoints"),
  successRateBasisPoints: int("successRateBasisPoints"),
  minDepositUsd: decimal("minDepositUsd", { precision: 10, scale: 2 }),
  totalOrdersLabel: varchar("totalOrdersLabel", { length: 40 }),
  activeServicesCount: int("activeServicesCount").default(0).notNull(),
  refillPolicy: varchar("refillPolicy", { length: 180 }),
  paymentMethods: json("paymentMethods").$type<string[]>(),
  specialties: json("specialties").$type<string[]>(),
  strengths: json("strengths").$type<string[]>(),
  auditSignals: json("auditSignals").$type<Record<string, number>>(),
  sourceUpdatedAt: timestamp("sourceUpdatedAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
}, table => [uniqueIndex("provider_slug_unique").on(table.slug), index("provider_status_score_idx").on(table.status, table.score)]);

export const serviceRecords = mysqlTable("service_records", {
  id: int("id").autoincrement().primaryKey(),
  providerId: int("providerId").notNull().references(() => providerRecords.id, { onDelete: "cascade" }),
  externalId: varchar("externalId", { length: 160 }),
  slug: varchar("slug", { length: 190 }).notNull(),
  platform: varchar("platform", { length: 80 }).notNull(),
  category: varchar("category", { length: 120 }).notNull(),
  name: varchar("name", { length: 300 }).notNull(),
  status: mysqlEnum("status", ["draft", "active", "paused", "archived"]).default("draft").notNull(),
  pricePerThousandUsd: decimal("pricePerThousandUsd", { precision: 12, scale: 4 }).notNull(),
  minOrder: int("minOrder").notNull(),
  maxOrder: int("maxOrder").notNull(),
  startMinutesMin: int("startMinutesMin"),
  startMinutesMax: int("startMinutesMax"),
  deliveryMinutesMin: int("deliveryMinutesMin"),
  deliveryMinutesMax: int("deliveryMinutesMax"),
  refillMode: mysqlEnum("refillMode", ["none", "manual", "automatic", "lifetime", "unknown"]).default("unknown").notNull(),
  refillDays: int("refillDays"),
  countryCode: varchar("countryCode", { length: 2 }),
  reviewStatus: mysqlEnum("reviewStatus", ["pending", "approved", "changes_requested"]).default("pending").notNull(),
  revision: int("revision").default(1).notNull(),
  normalizationVersion: int("normalizationVersion").default(0).notNull(),
  incomplete: boolean("incomplete").default(true).notNull(),
  sourceData: json("sourceData").$type<Record<string, string | number | boolean | null>>(),
  originalSourceData: json("originalSourceData").$type<Record<string, string | number | boolean | null>>(),
  sourceHash: varchar("sourceHash", { length: 64 }),
  sourceUrl: varchar("sourceUrl", { length: 500 }),
  sourceKind: mysqlEnum("sourceKind", ["legacy", "provider_api"]).default("legacy").notNull(),
  classificationNotes: json("classificationNotes").$type<string[]>(),
  pricingConfirmed: boolean("pricingConfirmed").default(false).notNull(),
  policyReviewed: boolean("policyReviewed").default(false).notNull(),
  evidenceUrl: varchar("evidenceUrl", { length: 500 }),
  priceCheckedAt: timestamp("priceCheckedAt"),
  reviewedAt: timestamp("reviewedAt"),
  reviewedByUserId: int("reviewedByUserId").references(() => users.id, { onDelete: "set null" }),
  reviewReason: text("reviewReason"),
  available: boolean("available").default(true).notNull(),
  missingSourceAt: timestamp("missingSourceAt"),
  lastPriceChangeAt: timestamp("lastPriceChangeAt"),
  quality: mysqlEnum("quality", ["standard", "premium", "elite"]).default("standard").notNull(),
  retentionBasisPoints: int("retentionBasisPoints"),
  featured: boolean("featured").default(false).notNull(),
  sourceUpdatedAt: timestamp("sourceUpdatedAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
}, table => [uniqueIndex("service_provider_slug_unique").on(table.providerId, table.slug), index("service_marketplace_idx").on(table.status, table.platform, table.category),
  index("service_provider_id_idx").on(table.providerId, table.id),
  index("service_status_id_idx").on(table.status, table.id),
  index("service_platform_id_idx").on(table.platform, table.id),
  index("service_public_featured_idx").on(table.status, table.featured, table.id),
  index("service_public_price_idx").on(table.status, table.pricePerThousandUsd, table.id),
  index("service_provider_external_idx").on(table.providerId, table.externalId),
  index("service_review_id_idx").on(table.reviewStatus, table.id),
  index("service_normalization_id_idx").on(table.normalizationVersion, table.id),
  index("service_incomplete_id_idx").on(table.incomplete, table.id),
  index("service_available_id_idx").on(table.available, table.id),
  index("service_price_change_idx").on(table.lastPriceChangeAt, table.id)]);

export const teamMembers = mysqlTable("team_members", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").references(() => users.id, { onDelete: "set null" }),
  email: varchar("email", { length: 320 }).notNull(),
  role: mysqlEnum("role", ["owner", "administrator", "operations_manager", "provider_reviewer", "catalogue_editor", "translation_manager", "auditor"]).notNull(),
  status: mysqlEnum("status", ["invited", "active", "suspended"]).default("invited").notNull(),
  invitedByUserId: int("invitedByUserId").references(() => users.id, { onDelete: "set null" }),
  invitationTokenHash: varchar("invitationTokenHash", { length: 128 }),
  invitationExpiresAt: timestamp("invitationExpiresAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
}, table => [uniqueIndex("team_member_email_unique").on(table.email), index("team_member_user_status_idx").on(table.userId, table.status)]);

export const auditEntries = mysqlTable("audit_entries", {
  id: int("id").autoincrement().primaryKey(),
  actorUserId: int("actorUserId").references(() => users.id, { onDelete: "set null" }),
  action: varchar("action", { length: 160 }).notNull(),
  entityType: varchar("entityType", { length: 80 }).notNull(),
  entityId: varchar("entityId", { length: 160 }).notNull(),
  summary: varchar("summary", { length: 500 }).notNull(),
  metadata: json("metadata").$type<Record<string, unknown>>(),
  ipAddress: varchar("ipAddress", { length: 64 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
}, table => [index("audit_entity_idx").on(table.entityType, table.entityId), index("audit_actor_created_idx").on(table.actorUserId, table.createdAt)]);

export const providerIntegrations = mysqlTable("provider_integrations", {
  id: int("id").autoincrement().primaryKey(),
  providerId: int("providerId").notNull().references(() => providerRecords.id, { onDelete: "cascade" }),
  name: varchar("name", { length: 160 }).notNull(),
  baseUrl: varchar("baseUrl", { length: 500 }).notNull(),
  credentialReference: varchar("credentialReference", { length: 240 }),
  credentialCiphertext: text("credentialCiphertext"),
  credentialIv: varchar("credentialIv", { length: 64 }),
  credentialTag: varchar("credentialTag", { length: 64 }),
  credentialVersion: int("credentialVersion").default(1).notNull(),
  status: mysqlEnum("status", ["disabled", "active", "error"]).default("disabled").notNull(),
  syncIntervalMinutes: int("syncIntervalMinutes").default(360).notNull(),
  nextSyncAt: timestamp("nextSyncAt"),
  syncLockUntil: timestamp("syncLockUntil"),
  consecutiveFailures: int("consecutiveFailures").default(0).notNull(),
  lastSyncedAt: timestamp("lastSyncedAt"),
  lastError: text("lastError"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
}, table => [index("integration_provider_status_idx").on(table.providerId, table.status), index("integration_due_idx").on(table.status, table.nextSyncAt)]);

// Durable jobs contain references and progress only; credentials remain in the encrypted vault.
export const providerSyncJobs = mysqlTable("provider_sync_jobs", {
  id: int("id").autoincrement().primaryKey(),
  integrationId: int("integrationId").notNull().references(() => providerIntegrations.id, { onDelete: "cascade" }),
  providerId: int("providerId").notNull().references(() => providerRecords.id, { onDelete: "cascade" }),
  activeProviderId: int("activeProviderId"),
  actorUserId: int("actorUserId").references(() => users.id, { onDelete: "set null" }),
  scheduled: boolean("scheduled").default(false).notNull(),
  configFingerprint: varchar("configFingerprint", { length: 64 }).notNull(),
  sourceUrl: varchar("sourceUrl", { length: 500 }).notNull(),
  status: mysqlEnum("status", ["queued", "preparing", "importing", "reconciling", "completed", "completed_with_issues", "failed"]).default("queued").notNull(),
  totalCount: int("totalCount").default(0).notNull(),
  processedCount: int("processedCount").default(0).notNull(),
  invalidCount: int("invalidCount").default(0).notNull(),
  reviewCount: int("reviewCount").default(0).notNull(),
  priceChangeCount: int("priceChangeCount").default(0).notNull(),
  missingCount: int("missingCount").default(0).notNull(),
  leaseToken: varchar("leaseToken", { length: 36 }),
  leaseUntil: timestamp("leaseUntil"),
  snapshotAt: timestamp("snapshotAt"),
  startedAt: timestamp("startedAt"),
  finishedAt: timestamp("finishedAt"),
  lastError: varchar("lastError", { length: 500 }),
  stagingCleared: boolean("stagingCleared").default(false).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
}, table => [uniqueIndex("sync_active_provider_unique").on(table.activeProviderId),
  index("sync_integration_id_idx").on(table.integrationId, table.id),
  index("sync_claim_idx").on(table.status, table.leaseUntil, table.id),
  index("sync_cleanup_idx").on(table.stagingCleared, table.activeProviderId, table.id)]);

// Short-lived, validated snapshots enable checkpoint recovery and complete-snapshot removal checks.
export const providerSyncRows = mysqlTable("provider_sync_rows", {
  jobId: int("jobId").notNull().references(() => providerSyncJobs.id, { onDelete: "cascade" }),
  ordinal: int("ordinal").notNull(),
  invalid: boolean("invalid").default(false).notNull(),
  externalId: varchar("externalId", { length: 160 }).notNull(),
  payload: json("payload").notNull(),
}, table => [primaryKey({ columns: [table.jobId, table.ordinal] }),
  uniqueIndex("sync_row_external_unique").on(table.jobId, table.externalId),
  index("sync_row_issue_idx").on(table.jobId, table.invalid, table.ordinal)]);

export const priceSnapshots = mysqlTable("price_snapshots", {
  id: int("id").autoincrement().primaryKey(),
  serviceId: int("serviceId").notNull().references(() => serviceRecords.id, { onDelete: "cascade" }),
  pricePerThousandUsd: decimal("pricePerThousandUsd", { precision: 12, scale: 4 }).notNull(),
  capturedAt: timestamp("capturedAt").defaultNow().notNull(),
}, table => [index("price_service_captured_idx").on(table.serviceId, table.capturedAt)]);

export const localizedContent = mysqlTable("localized_content", {
  id: int("id").autoincrement().primaryKey(),
  entityType: mysqlEnum("entityType", ["provider", "service", "page"]).notNull(),
  entityId: varchar("entityId", { length: 160 }).notNull(),
  fieldName: varchar("fieldName", { length: 100 }).notNull(),
  locale: mysqlEnum("locale", ["en", "es", "ar", "hi", "zh"]).notNull(),
  value: text("value").notNull(),
  status: mysqlEnum("status", ["draft", "machine_translated", "reviewed", "published"]).default("draft").notNull(),
  updatedByUserId: int("updatedByUserId").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
}, table => [uniqueIndex("localized_content_unique").on(table.entityType, table.entityId, table.fieldName, table.locale), index("localized_status_idx").on(table.locale, table.status)]);

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;
export type StaffAccount = typeof staffAccounts.$inferSelect;
export type ProviderRecord = typeof providerRecords.$inferSelect;
export type ServiceRecord = typeof serviceRecords.$inferSelect;
export type TeamMember = typeof teamMembers.$inferSelect;
export type TeamRole = TeamMember["role"];
export type AuditEntry = typeof auditEntries.$inferSelect;
