import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { providers, services } from "@/data/marketplace";
import { BadgeCheck, Languages, Layers3, ScrollText, ShieldCheck, Users } from "lucide-react";
import { useRoute } from "wouter";

const modules = {
  providers: { title: "Provider operations", subtitle: "Verification, risk state and ownership", icon: BadgeCheck },
  services: { title: "Service catalogue", subtitle: "Pricing freshness, classification and publishing", icon: Layers3 },
  team: { title: "Team & access", subtitle: "Roles, permissions and account status", icon: Users },
  translations: { title: "Translation workspace", subtitle: "Review status across supported markets", icon: Languages },
  audit: { title: "Audit log", subtitle: "Immutable record of administrative actions", icon: ScrollText },
} as const;

export default function AdminModule(){const [,params]=useRoute("/admin/:module");const key=(params?.module??"providers") as keyof typeof modules;const config=modules[key]??modules.providers;const Icon=config.icon;return <DashboardLayout><div className="mx-auto max-w-[1450px] p-2 sm:p-5"><div className="flex items-center gap-4 border-b border-slate-200 pb-6"><div className="grid size-12 place-items-center rounded-2xl bg-blue-50 text-blue-700"><Icon/></div><div><p className="text-xs font-bold uppercase tracking-[.18em] text-cyan-700">Beacon Control Center</p><h1 className="mt-1 text-3xl font-extrabold text-slate-950">{config.title}</h1><p className="mt-1 text-sm text-slate-500">{config.subtitle}</p></div></div><div className="mt-6">{key==="providers"?<ProviderTable/>:key==="services"?<ServiceTable/>:key==="team"?<TeamTable/>:key==="translations"?<TranslationTable/>:<AuditTable/>}</div></div></DashboardLayout>}
function Shell({headers,children}:{headers:string[];children:React.ReactNode}){return <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[800px]"><thead><tr className="border-b border-slate-200 bg-slate-50">{headers.map(h=><th key={h} className="px-5 py-3 text-start text-[10px] uppercase tracking-wider text-slate-400">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{children}</tbody></table></div></div>}
function ProviderTable(){return <Shell headers={["Provider","Status","Beacon score","Success","Last update"]}>{providers.map(p=><tr key={p.id}><td className="px-5 py-4 font-bold text-slate-900">{p.name}<p className="mt-1 text-xs font-normal text-slate-400">{p.location}</p></td><td className="px-5 py-4"><Badge className={p.verified?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}>{p.verified?"Verified":"Review due"}</Badge></td><td className="px-5 py-4 font-extrabold">{p.score}</td><td className="px-5 py-4 text-sm text-slate-600">{p.successRate}%</td><td className="px-5 py-4 text-sm text-slate-500">{p.updatedMinutes} min ago</td></tr>)}</Shell>}
function ServiceTable(){return <Shell headers={["Service","Provider","Price / 1K","Retention","Publishing"]}>{services.map(s=>{const p=providers.find(x=>x.id===s.providerId)!;return <tr key={s.id}><td className="px-5 py-4 font-bold text-slate-900">{s.name}<p className="mt-1 text-xs font-normal text-slate-400">{s.platform} · {s.category}</p></td><td className="px-5 py-4 text-sm text-slate-600">{p.name}</td><td className="px-5 py-4 font-extrabold">${s.pricePerThousand.toFixed(2)}</td><td className="px-5 py-4 text-sm">{s.retention}%</td><td className="px-5 py-4"><Badge className="bg-emerald-50 text-emerald-700">Published</Badge></td></tr>})}</Shell>}
function TeamTable(){const rows=[["Nadia Rahman","Operations Manager","Full provider operations","Active"],["Marcus Lee","Provider Reviewer","Verification & complaints","Active"],["Priya Shah","Translation Manager","Localization only","Active"],["Kenji Watanabe","Read-only Auditor","Reports & audit log","Active"]];return <Shell headers={["Member","Role","Access scope","Status"]}>{rows.map(r=><tr key={r[0]}>{r.map((v,i)=><td key={v} className={`px-5 py-4 text-sm ${i===0?"font-bold text-slate-900":"text-slate-600"}`}>{v}</td>)}</tr>)}</Shell>}
function TranslationTable(){const rows=[["English","100%","Source","Published"],["Spanish (Panama)","96%","Human reviewed","Published"],["Arabic","92%","RTL reviewed","Published"],["Hindi","78%","Review pending","Draft"],["Simplified Chinese","85%","Human reviewed","Published"]];return <Shell headers={["Language","Coverage","Review state","Publishing"]}>{rows.map(r=><tr key={r[0]}>{r.map((v,i)=><td key={v} className={`px-5 py-4 text-sm ${i===0?"font-bold text-slate-900":"text-slate-600"}`}>{v}</td>)}</tr>)}</Shell>}
function AuditTable(){const rows=[["07:08:22","provider.verify","Nadia Rahman","Northstar Social","Allowed"],["06:56:03","service.price.update","System sync","Instagram Followers","Allowed"],["06:41:19","team.role.update","Anas Alkasem","Kenji Watanabe","Allowed"],["06:22:47","finance.export","Marcus Lee","Monthly report","Denied"]];return <Shell headers={["Time (UTC)","Action","Actor","Resource","Result"]}>{rows.map(r=><tr key={r.join()}>{r.map((v,i)=><td key={`${i}-${v}`} className={`px-5 py-4 text-sm ${i===1?"font-mono text-xs":i===4&&v==="Denied"?"font-bold text-red-600":"text-slate-600"}`}>{v}</td>)}</tr>)}</Shell>}
