import DashboardLayout from "@/components/DashboardLayout";
import ProviderIntegrationVault from "@/components/ProviderIntegrationVault";
import TeamAccessTable from "@/components/TeamAccessTable";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { useAdminText, type AdminTextKey } from "@/i18n/admin";
import { useLocale } from "@/contexts/LocaleContext";
import { BadgeCheck, Database, KeyRound, Languages, Layers3, Loader2, RefreshCw, ScrollText, ShieldCheck, Sparkles, Users } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { useRoute } from "wouter";

const modules = {
  providers: { title: "providerOperations" as AdminTextKey, subtitle: "providerSubtitle" as AdminTextKey, icon: BadgeCheck },
  services: { title: "serviceCatalogue" as AdminTextKey, subtitle: "serviceSubtitle" as AdminTextKey, icon: Layers3 },
  integrations: { title: "integrationTitle" as AdminTextKey, subtitle: "integrationSubtitle" as AdminTextKey, icon: KeyRound },
  team: { title: "teamTitle" as AdminTextKey, subtitle: "teamSubtitle" as AdminTextKey, icon: Users },
  translations: { title: "translationTitle" as AdminTextKey, subtitle: "translationSubtitle" as AdminTextKey, icon: Languages },
  audit: { title: "auditTitle" as AdminTextKey, subtitle: "auditSubtitle" as AdminTextKey, icon: ScrollText },
} as const;

type ModuleKey = keyof typeof modules;
type TeamRole = "administrator" | "operations_manager" | "provider_reviewer" | "catalogue_editor" | "translation_manager" | "auditor";
const roleKeys: Record<string, AdminTextKey> = { owner: "owner", administrator: "administrator", operations_manager: "operationsManager", provider_reviewer: "providerReviewer", catalogue_editor: "catalogueEditor", translation_manager: "translationManager", auditor: "auditor" };

export default function AdminModule() {
  const [, params] = useRoute("/admin/:module"); const key = (params?.module ?? "providers") as ModuleKey; const config = modules[key] ?? modules.providers; const Icon = config.icon;
  const text = useAdminText();
  return <DashboardLayout><div className="mx-auto max-w-[1450px] p-2 sm:p-5"><div className="flex items-center gap-4 border-b border-slate-200 pb-6"><div className="grid size-12 place-items-center rounded-2xl bg-blue-50 text-blue-700"><Icon/></div><div><p className="text-xs font-bold uppercase tracking-[.18em] text-cyan-700">{text("controlCenter")}</p><h1 className="mt-1 text-3xl font-extrabold text-slate-950">{text(config.title)}</h1><p className="mt-1 text-sm text-slate-500">{text(config.subtitle)}</p></div></div><div className="mt-6">{key === "providers" ? <ProviderTable/> : key === "services" ? <ServiceTable/> : key === "integrations" ? <ProviderIntegrationVault/> : key === "team" ? <TeamAccessTable/> : key === "translations" ? <TranslationTable/> : <AuditTable/>}</div></div></DashboardLayout>;
}

function Shell({ headers, children }: { headers: string[]; children: React.ReactNode }) { return <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[800px]"><thead><tr className="border-b border-slate-200 bg-slate-50">{headers.map(h => <th key={h} className="px-5 py-3 text-start text-[10px] uppercase tracking-wider text-slate-400">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{children}</tbody></table></div></div>; }
function EmptyRow({ columns, children }: { columns: number; children: React.ReactNode }) { return <tr><td colSpan={columns} className="px-5 py-14 text-center text-sm text-slate-500">{children}</td></tr>; }
function ProviderTable() {
  const text = useAdminText(); const { locale } = useLocale();
  const utils = trpc.useUtils(); const access = trpc.admin.access.useQuery(); const query = trpc.admin.providers.list.useQuery(undefined, { retry: false });
  const statusMutation = trpc.admin.providers.setStatus.useMutation({ onSuccess: async () => { toast.success(text("providerUpdated")); await Promise.all([utils.admin.providers.list.invalidate(), utils.marketplace.snapshot.invalidate(), utils.admin.audit.list.invalidate()]); }, onError: error => toast.error(error.message) });
  const aiMutation = trpc.admin.ai.analyzeProvider.useMutation({ onSuccess: () => utils.admin.audit.list.invalidate(), onError: error => toast.error(error.message) });
  const canReview = access.data?.permissions.includes("providers.review");
  return <div className="space-y-5">{aiMutation.data && <section className="rounded-2xl border border-cyan-200 bg-cyan-50/60 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2 font-extrabold text-slate-950"><Sparkles className="size-5 text-cyan-700"/>{text("aiAnalysis")}</div><div className="flex gap-2"><Badge>{text("riskLevel")}: {aiMutation.data.riskLevel}</Badge><Badge variant="outline">{text("confidence")}: {aiMutation.data.confidence}%</Badge></div></div><p className="mt-4 leading-7 text-slate-700">{aiMutation.data.summary}</p><ul className="mt-4 grid gap-2 text-sm text-slate-600 sm:grid-cols-2">{aiMutation.data.signals.map(signal => <li key={signal} className="rounded-xl bg-white p-3">{signal}</li>)}</ul><p className="mt-4 text-sm font-semibold text-cyan-900">{text("recommendedAction")}: {aiMutation.data.recommendedAction.replaceAll("_", " ")}</p><p className="mt-2 text-xs text-slate-500">{text("aiAdvisory")} · {aiMutation.data.model}</p></section>}<Shell headers={[text("provider"),text("status"),text("beaconScore"),text("success"),text("lastUpdate")]}>{query.isLoading ? <EmptyRow columns={5}><Loader2 className="mx-auto size-5 animate-spin"/></EmptyRow> : query.data?.map(provider => <tr key={provider.id}><td className="px-5 py-4 font-bold text-slate-900">{provider.name}<p className="mt-1 text-xs font-normal text-slate-400">{provider.location}</p>{canReview && <Button className="mt-2 h-7 px-2 text-xs" variant="outline" size="sm" disabled={aiMutation.isPending} onClick={() => aiMutation.mutate({ providerId: provider.id, locale })}>{aiMutation.isPending && aiMutation.variables?.providerId === provider.id ? <Loader2 className="size-3 animate-spin"/> : <Sparkles className="size-3"/>}{text("analyze")}</Button>}</td><td className="px-5 py-4">{canReview ? <Select value={provider.status} onValueChange={status => statusMutation.mutate({ id: provider.id, status: status as "draft" | "pending_review" | "active" | "suspended" })}><SelectTrigger className="w-44"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="draft">{text("draft")}</SelectItem><SelectItem value="pending_review">{text("pendingReview")}</SelectItem><SelectItem value="active">{text("active")}</SelectItem><SelectItem value="suspended">{text("suspended")}</SelectItem></SelectContent></Select> : <Badge>{text(provider.status === "pending_review" ? "pendingReview" : provider.status)}</Badge>}</td><td className="px-5 py-4 font-extrabold">{provider.score}</td><td className="px-5 py-4 text-sm text-slate-600">{((provider.successRateBasisPoints ?? 0) / 100).toFixed(1)}%</td><td className="px-5 py-4 text-sm text-slate-500">{new Date(provider.updatedAt).toLocaleString()}</td></tr>)}</Shell></div>;
}
function ServiceTable() {
  const text = useAdminText();
  const utils = trpc.useUtils(); const access = trpc.admin.access.useQuery(); const query = trpc.admin.services.list.useQuery(undefined, { retry: false }); const providerQuery = trpc.admin.providers.list.useQuery(undefined, { retry: false });
  const mutation = trpc.admin.services.update.useMutation({ onSuccess: async () => { toast.success(text("serviceUpdated")); await Promise.all([utils.admin.services.list.invalidate(), utils.marketplace.snapshot.invalidate(), utils.admin.audit.list.invalidate()]); }, onError: error => toast.error(error.message) });
  const canWrite = access.data?.permissions.includes("services.write"); const names = new Map(providerQuery.data?.map(provider => [provider.id, provider.name]));
  return <Shell headers={[text("service"),text("provider"),text("price"),text("quality"),text("publishing")]}>{query.isLoading ? <EmptyRow columns={5}><Loader2 className="mx-auto size-5 animate-spin"/></EmptyRow> : query.data?.map(service => <tr key={service.id}><td className="px-5 py-4 font-bold text-slate-900">{service.name}<p className="mt-1 text-xs font-normal text-slate-400">{service.platform} · {service.category}</p></td><td className="px-5 py-4 text-sm text-slate-600">{names.get(service.providerId) ?? `${text("provider")} #${service.providerId}`}</td><td className="px-5 py-4">{canWrite ? <Input className="w-28" type="number" min="0.0001" step="0.0001" defaultValue={service.pricePerThousandUsd} onBlur={event => { const next = Number(event.target.value); if (Number.isFinite(next) && next > 0 && next !== Number(service.pricePerThousandUsd)) mutation.mutate({ id: service.id, pricePerThousandUsd: next }); }}/> : <bdi className="font-extrabold">${Number(service.pricePerThousandUsd).toFixed(2)}</bdi>}</td><td className="px-5 py-4 text-sm capitalize">{service.quality}</td><td className="px-5 py-4">{canWrite ? <Select value={service.status} onValueChange={status => mutation.mutate({ id: service.id, status: status as "draft" | "active" | "paused" | "archived" })}><SelectTrigger className="w-36"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="draft">{text("draft")}</SelectItem><SelectItem value="active">{text("active")}</SelectItem><SelectItem value="paused">{text("paused")}</SelectItem><SelectItem value="archived">{text("archived")}</SelectItem></SelectContent></Select> : <Badge>{text(service.status)}</Badge>}</td></tr>)}</Shell>;
}

function IntegrationVault() {
  const text = useAdminText(); const utils = trpc.useUtils();
  const access = trpc.admin.access.useQuery(); const providers = trpc.admin.providers.list.useQuery(undefined, { retry: false }); const integrations = trpc.admin.integrations.list.useQuery(undefined, { retry: false });
  const [id, setId] = useState<number | undefined>(); const [providerId, setProviderId] = useState(""); const [name, setName] = useState(""); const [baseUrl, setBaseUrl] = useState(""); const [apiKey, setApiKey] = useState(""); const [interval, setInterval] = useState("360"); const [enabled, setEnabled] = useState(true);
  const reset = () => { setId(undefined); setProviderId(""); setName(""); setBaseUrl(""); setApiKey(""); setInterval("360"); setEnabled(true); };
  const refresh = () => Promise.all([utils.admin.integrations.list.invalidate(), utils.admin.audit.list.invalidate()]);
  const save = trpc.admin.integrations.save.useMutation({ onSuccess: async () => { toast.success(text(id ? "integrationUpdated" : "integrationSaved")); reset(); await refresh(); }, onError: error => toast.error(error.message) });
  const sync = trpc.admin.integrations.syncNow.useMutation({ onSuccess: async data => { toast.success(`${text("importedServices")}: ${"importedCount" in data ? data.importedCount : 0} · ${text("pendingReview")}: ${"reviewCount" in data ? data.reviewCount : 0}`); await Promise.all([refresh(), utils.admin.services.list.invalidate(), utils.marketplace.snapshot.invalidate()]); }, onError: error => toast.error(error.message) });
  const toggle = trpc.admin.integrations.setEnabled.useMutation({ onSuccess: refresh, onError: error => toast.error(error.message) });
  const canWrite = access.data?.permissions.includes("integrations.write");
  return <div className="space-y-5">{canWrite && <form className="rounded-2xl border border-cyan-200 bg-cyan-50/40 p-5 shadow-sm" onSubmit={event => { event.preventDefault(); save.mutate({ id, providerId: Number(providerId), name, baseUrl, apiKey: apiKey || undefined, syncIntervalMinutes: Number(interval), enabled }); }}><div className="flex items-start gap-3"><div className="grid size-10 place-items-center rounded-xl bg-white text-cyan-700"><KeyRound className="size-5"/></div><div><h2 className="font-extrabold text-slate-950">{text("integrationTitle")}</h2><p className="mt-1 text-sm text-slate-500">{text("vaultBody")}</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-2"><Select value={providerId} onValueChange={setProviderId}><SelectTrigger><SelectValue placeholder={text("provider")}/></SelectTrigger><SelectContent>{providers.data?.map(provider => <SelectItem key={provider.id} value={String(provider.id)}>{provider.name}</SelectItem>)}</SelectContent></Select><Input value={name} onChange={event => setName(event.target.value)} placeholder={text("integrationName")} required/><Input dir="ltr" className="md:col-span-2" type="url" value={baseUrl} onChange={event => setBaseUrl(event.target.value)} placeholder="https://provider.example/api/v2" required/><label className="grid gap-1"><Input dir="ltr" type="password" autoComplete="off" value={apiKey} onChange={event => setApiKey(event.target.value)} placeholder={text("apiKey")} required={!id}/>{id && <span className="text-xs text-slate-500">{text("keyOptional")}</span>}</label><Select value={interval} onValueChange={setInterval}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="60">{text("everyHour")}</SelectItem><SelectItem value="360">{text("every6Hours")}</SelectItem><SelectItem value="720">{text("every12Hours")}</SelectItem><SelectItem value="1440">{text("everyDay")}</SelectItem><SelectItem value="10080">{text("everyWeek")}</SelectItem></SelectContent></Select><label className="flex items-center justify-between rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700 md:col-span-2"><span>{text("scheduledSync")}</span><Switch checked={enabled} onCheckedChange={setEnabled}/></label><Button className="md:col-span-2" disabled={save.isPending || !providerId}>{save.isPending && <Loader2 className="size-4 animate-spin"/>}{text("saveCredential")}</Button></div></form>}
    <Shell headers={[text("integrationName"),text("provider"),text("scheduledSync"),text("lastSync"),text("nextSync")]}>{integrations.isLoading ? <EmptyRow columns={5}><Loader2 className="mx-auto size-5 animate-spin"/></EmptyRow> : integrations.data?.length ? integrations.data.map(item => <tr key={item.id}><td className="px-5 py-4"><div className="font-bold text-slate-900">{item.name}</div><div dir="ltr" className="mt-1 max-w-sm truncate text-xs text-slate-400">{item.baseUrl}</div><div className="mt-2 text-xs text-emerald-700">{item.credentialHint ?? text("credentialHint")}</div>{item.lastError && <p className="mt-2 max-w-md text-xs text-red-600">{item.lastError}</p>}</td><td className="px-5 py-4 text-sm text-slate-600">{item.providerName}</td><td className="px-5 py-4"><div className="flex items-center gap-3"><Switch checked={item.status === "active"} disabled={!canWrite || toggle.isPending} onCheckedChange={value => toggle.mutate({ id: item.id, enabled: value })}/><Badge>{item.status === "active" ? text("enabled") : text("disabled")}</Badge></div></td><td className="px-5 py-4 text-sm text-slate-500">{item.lastSyncedAt ? new Date(item.lastSyncedAt).toLocaleString() : text("never")}</td><td className="px-5 py-4"><p className="text-sm text-slate-500">{item.nextSyncAt ? new Date(item.nextSyncAt).toLocaleString() : text("never")}</p>{canWrite && <div className="mt-2 flex gap-2"><Button size="sm" variant="outline" onClick={() => sync.mutate({ id: item.id })} disabled={sync.isPending}>{sync.isPending && sync.variables?.id === item.id ? <Loader2 className="size-3 animate-spin"/> : <RefreshCw className="size-3"/>}{text("syncNow")}</Button><Button size="sm" variant="ghost" onClick={() => { setId(item.id); setProviderId(String(item.providerId)); setName(item.name); setBaseUrl(item.baseUrl); setApiKey(""); setInterval(String(item.syncIntervalMinutes)); setEnabled(item.status === "active"); window.scrollTo({ top: 0, behavior: "smooth" }); }}>{text("integrationUpdated")}</Button></div>}</td></tr>) : <EmptyRow columns={5}>{text("noIntegrations")}</EmptyRow>}</Shell>
  </div>;
}

function TeamTable() {
  const text = useAdminText();
  const utils = trpc.useUtils(); const access = trpc.admin.access.useQuery(); const team = trpc.admin.team.list.useQuery(undefined, { retry: false });
  const [email, setEmail] = useState(""); const [role, setRole] = useState<TeamRole>("provider_reviewer");
  const invite = trpc.admin.team.invite.useMutation({ onSuccess: async () => { toast.success(text("invitationRecorded")); setEmail(""); await utils.admin.team.list.invalidate(); }, onError: error => toast.error(error.message) });
  const canInvite = access.data?.permissions.includes("team.write");
  return <div className="space-y-5">{canInvite && <form className="rounded-2xl border border-blue-100 bg-blue-50/50 p-5" onSubmit={event => { event.preventDefault(); invite.mutate({ email, role }); }}><div className="flex items-start gap-3"><div className="grid size-10 place-items-center rounded-xl bg-white text-blue-700"><ShieldCheck className="size-5"/></div><div><h2 className="font-extrabold text-slate-950">{text("inviteTitle")}</h2><p className="mt-1 text-sm text-slate-500">{text("inviteBody")}</p></div></div><div className="mt-4 grid gap-3 md:grid-cols-2"><Input className="min-w-0 flex-1" dir="ltr" type="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="team.member@example.com" required/><Select value={role} onValueChange={value => setRole(value as TeamRole)}><SelectTrigger className="w-full lg:w-60"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(roleKeys).filter(([value]) => value !== "owner").map(([value,key]) => <SelectItem key={value} value={value}>{text(key)}</SelectItem>)}</SelectContent></Select><Button className="md:col-span-2" disabled={invite.isPending}>{invite.isPending && <Loader2 className="size-4 animate-spin"/>}{text("inviteMember")}</Button></div>{invite.data && <div className="mt-4 rounded-xl border border-emerald-200 bg-white p-3"><p className="mb-2 text-xs font-bold text-emerald-800">{text("inviteLink")}</p><div className="flex gap-2"><Input dir="ltr" readOnly value={`${window.location.origin}/team/accept?token=${invite.data.token}`}/><Button type="button" variant="outline" onClick={() => navigator.clipboard.writeText(`${window.location.origin}/team/accept?token=${invite.data.token}`)}>{text("copyLink")}</Button></div></div>}</form>}
    <Shell headers={[text("member"),text("role"),text("accessStatus"),text("added")]}>{team.isLoading ? <EmptyRow columns={4}><Loader2 className="mx-auto size-5 animate-spin"/></EmptyRow> : team.isError ? <EmptyRow columns={4}>{text("noTeamPermission")}</EmptyRow> : team.data?.length ? team.data.map(member => <tr key={member.id}><td dir="ltr" className="px-5 py-4 text-start font-bold text-slate-900">{member.email}</td><td className="px-5 py-4 text-sm text-slate-600">{text(roleKeys[member.role])}</td><td className="px-5 py-4"><Badge className={member.status === "active" ? "bg-emerald-50 text-emerald-700" : member.status === "suspended" ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-700"}>{member.status}</Badge></td><td className="px-5 py-4 text-sm text-slate-500">{new Date(member.createdAt).toLocaleString()}</td></tr>) : <EmptyRow columns={4}>{text("noInvites")}</EmptyRow>}</Shell></div>;
}

function TranslationTable() {
  const text = useAdminText(); const utils = trpc.useUtils(); const access = trpc.admin.access.useQuery(); const list = trpc.admin.translations.list.useQuery(undefined, { retry: false });
  const [entityType, setEntityType] = useState<"provider" | "service" | "page">("page"); const [entityId, setEntityId] = useState("home"); const [fieldName, setFieldName] = useState("heroTitle"); const [locale, setLocale] = useState<"en" | "es" | "ar" | "hi" | "zh">("ar"); const [status, setStatus] = useState<"draft" | "machine_translated" | "reviewed" | "published">("reviewed"); const [value, setValue] = useState("");
  const mutation = trpc.admin.translations.upsert.useMutation({ onSuccess: async () => { toast.success(text("translationSaved")); setValue(""); await Promise.all([utils.admin.translations.list.invalidate(), utils.admin.audit.list.invalidate()]); }, onError: error => toast.error(error.message) });
  const canWrite = access.data?.permissions.includes("translations.write");
  return <div className="space-y-5">{canWrite && <form className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm" onSubmit={event => { event.preventDefault(); mutation.mutate({ entityType, entityId, fieldName, locale, status, value }); }}><div className="grid gap-3 md:grid-cols-5"><Select value={entityType} onValueChange={item => setEntityType(item as typeof entityType)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["page","provider","service"].map(item => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select><Input value={entityId} onChange={event => setEntityId(event.target.value)} placeholder={text("entityId")} required/><Input value={fieldName} onChange={event => setFieldName(event.target.value)} placeholder={text("fieldName")} required/><Select value={locale} onValueChange={item => setLocale(item as typeof locale)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["en","es","ar","hi","zh"].map(item => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select><Select value={status} onValueChange={item => setStatus(item as typeof status)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="draft">{text("draft")}</SelectItem><SelectItem value="machine_translated">{text("machineTranslated")}</SelectItem><SelectItem value="reviewed">{text("reviewed")}</SelectItem><SelectItem value="published">{text("published")}</SelectItem></SelectContent></Select></div><Textarea dir={locale === "ar" ? "rtl" : "ltr"} className="mt-3 min-h-28" value={value} onChange={event => setValue(event.target.value)} placeholder={text("translationValue")} required/><Button className="mt-3" disabled={mutation.isPending}>{mutation.isPending && <Loader2 className="size-4 animate-spin"/>}{text("saveTranslation")}</Button></form>}<Shell headers={[text("entityType"),text("entityId"),text("fieldName"),text("locale"),text("reviewState")]}>{list.isLoading ? <EmptyRow columns={5}><Loader2 className="mx-auto size-5 animate-spin"/></EmptyRow> : list.data?.length ? list.data.map(item => <tr key={item.id}><td className="px-5 py-4 text-sm text-slate-600">{item.entityType}</td><td className="px-5 py-4 font-mono text-xs text-slate-700">{item.entityId}</td><td className="px-5 py-4 text-sm text-slate-600">{item.fieldName}</td><td className="px-5 py-4 font-bold text-slate-900">{item.locale}</td><td className="px-5 py-4"><Badge>{item.status}</Badge></td></tr>) : <EmptyRow columns={5}>{text("noTranslations")}</EmptyRow>}</Shell></div>;
}
function AuditTable() { const text = useAdminText(); const audit = trpc.admin.audit.list.useQuery({ limit: 100 }, { retry: false }); return <Shell headers={[text("time"),text("action"),text("resource"),text("summary")]}>{audit.isLoading ? <EmptyRow columns={4}><Loader2 className="mx-auto size-5 animate-spin"/></EmptyRow> : audit.isError ? <EmptyRow columns={4}>{text("noAuditPermission")}</EmptyRow> : audit.data?.length ? audit.data.map(entry => <tr key={entry.id}><td className="px-5 py-4 text-xs text-slate-500">{new Date(entry.createdAt).toLocaleString()}</td><td dir="ltr" className="px-5 py-4 text-start font-mono text-xs text-slate-700">{entry.action}</td><td dir="ltr" className="px-5 py-4 text-start text-sm text-slate-600">{entry.entityType}:{entry.entityId}</td><td className="px-5 py-4 text-sm text-slate-600">{entry.summary}</td></tr>) : <EmptyRow columns={4}>{text("noAudit")}</EmptyRow>}</Shell>; }
