import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { providers, services } from "@/data/marketplace";
import { Activity, AlertTriangle, ArrowUpRight, BadgeCheck, CheckCircle2, Clock3, Database, Eye, Languages, LockKeyhole, ShieldCheck, Users } from "lucide-react";
import { Link } from "wouter";

export default function Admin() {
  return <DashboardLayout><div className="mx-auto max-w-[1500px] p-2 sm:p-5"><div className="flex flex-col justify-between gap-5 border-b border-slate-200 pb-6 lg:flex-row lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-cyan-700">Beacon Control Center</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight text-slate-950">Operations overview</h1><p className="mt-2 text-sm text-slate-500">Provider integrity, catalogue freshness and team activity in one protected workspace.</p></div><div className="flex items-center gap-2"><Badge variant="outline" className="h-9 gap-2 rounded-xl border-emerald-200 bg-emerald-50 px-3 text-emerald-700"><span className="size-2 rounded-full bg-emerald-500"/>All systems operational</Badge><Button asChild className="rounded-xl bg-[#0B2A68]"><Link href="/admin/providers">Review queue</Link></Button></div></div>
    <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><AdminMetric icon={<BadgeCheck/>} label="Verified providers" value={`${providers.filter(p=>p.verified).length}`} change="+2 this month"/><AdminMetric icon={<Database/>} label="Published services" value={`${services.length}`} change="96.4% fresh"/><AdminMetric icon={<AlertTriangle/>} label="Needs review" value="7" change="3 high priority" warning/><AdminMetric icon={<Users/>} label="Active staff" value="12" change="4 roles configured"/></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.45fr_.85fr]"><section className="admin-panel"><div className="admin-panel-head"><div><h2>Provider review queue</h2><p>Risk-ranked items awaiting a decision.</p></div><Button variant="ghost" size="sm" asChild><Link href="/admin/providers">Open full queue<ArrowUpRight className="size-4"/></Link></Button></div><div className="overflow-x-auto"><table className="w-full min-w-[680px]"><thead><tr className="text-start text-[10px] uppercase tracking-wider text-slate-400"><th className="px-5 py-3 text-start">Provider</th><th className="px-5 py-3 text-start">Reason</th><th className="px-5 py-3 text-start">Risk</th><th className="px-5 py-3 text-start">Owner</th><th className="px-5 py-3 text-start">Due</th></tr></thead><tbody className="divide-y divide-slate-100">{[
      ["Atlas Growth","Identity documents updated","Medium","Nadia R.","Today"],["ViralGrid","Pricing anomaly detected","High","Marcus L.","2h"],["Orbit Reach","Verification renewal","Low","Priya S.","Tomorrow"],["Social Apex","Complaint threshold reached","High","Nadia R.","Now"]
    ].map(([name,reason,risk,owner,due])=><tr key={name} className="text-sm"><td className="px-5 py-4 font-bold text-slate-900">{name}</td><td className="px-5 py-4 text-slate-500">{reason}</td><td className="px-5 py-4"><RiskBadge risk={risk}/></td><td className="px-5 py-4 text-slate-600">{owner}</td><td className="px-5 py-4 font-semibold text-slate-700">{due}</td></tr>)}</tbody></table></div></section>
      <section className="admin-panel"><div className="admin-panel-head"><div><h2>Trust health</h2><p>Current scoring coverage.</p></div><ShieldCheck className="size-5 text-cyan-600"/></div><div className="space-y-5 p-5"><Health label="Price freshness" value={96}/><Health label="Provider identity" value={91}/><Health label="Service completeness" value={88}/><Health label="Review integrity" value={94}/></div><div className="mx-5 mb-5 rounded-xl bg-cyan-50 p-4 text-sm text-cyan-900"><strong>+4.8%</strong> trust coverage since last month.</div></section>
    </div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1fr_1fr]"><section className="admin-panel"><div className="admin-panel-head"><div><h2>Recent activity</h2><p>Immutable audit entries from authorized users.</p></div><Eye className="size-5 text-slate-400"/></div><div className="divide-y divide-slate-100">{[
      ["Provider approved","Northstar Social was renewed for 90 days","Nadia R.","4 min ago"],["Service price changed","Instagram Followers: $2.64 → $2.42","System sync","12 min ago"],["Role updated","Kenji W. assigned Translation Reviewer","Anas A.","31 min ago"],["Complaint resolved","Evidence reviewed and provider response accepted","Marcus L.","1h ago"]
    ].map(([title,detail,actor,time])=><div key={title} className="flex gap-3 p-5"><div className="mt-0.5 grid size-8 shrink-0 place-items-center rounded-lg bg-slate-100 text-slate-600"><Activity className="size-4"/></div><div className="min-w-0 flex-1"><p className="font-bold text-slate-900">{title}</p><p className="mt-1 text-xs text-slate-500">{detail}</p><p className="mt-2 text-[10px] font-semibold uppercase tracking-wide text-slate-400">{actor} · {time}</p></div></div>)}</div></section>
      <section className="admin-panel"><div className="admin-panel-head"><div><h2>Role access</h2><p>Least-privilege access across the team.</p></div><LockKeyhole className="size-5 text-slate-400"/></div><div className="grid gap-3 p-5">{[
        ["Operations Manager","4 members","Providers · Services · Reports"],["Provider Reviewer","3 members","Verification · Complaints"],["Translation Manager","2 members","Languages · Content"],["Read-only Auditor","3 members","Audit log · Reports"]
      ].map(([role,members,access])=><div key={role} className="flex items-center justify-between rounded-xl border border-slate-200 p-4"><div><p className="font-bold text-slate-900">{role}</p><p className="mt-1 text-xs text-slate-500">{access}</p></div><Badge variant="secondary" className="rounded-lg">{members}</Badge></div>)}</div></section></div>
  </div></DashboardLayout>;
}
function AdminMetric({icon,label,value,change,warning=false}:{icon:React.ReactNode;label:string;value:string;change:string;warning?:boolean}){return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div className={`grid size-10 place-items-center rounded-xl ${warning?"bg-amber-50 text-amber-600":"bg-blue-50 text-blue-700"}`}>{icon}</div><span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Live</span></div><p className="mt-5 text-3xl font-extrabold text-slate-950">{value}</p><p className="mt-1 text-sm font-semibold text-slate-600">{label}</p><p className={`mt-3 text-xs ${warning?"text-amber-700":"text-emerald-600"}`}>{change}</p></article>}
function RiskBadge({risk}:{risk:string}){const cls=risk==="High"?"bg-red-50 text-red-700":risk==="Medium"?"bg-amber-50 text-amber-700":"bg-slate-100 text-slate-600";return <span className={`rounded-full px-2.5 py-1 text-xs font-bold ${cls}`}>{risk}</span>}
function Health({label,value}:{label:string;value:number}){return <div><div className="flex justify-between text-sm"><span className="font-semibold text-slate-600">{label}</span><strong>{value}%</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-blue-600 to-teal-400" style={{width:`${value}%`}}/></div></div>}
