import { ProviderAvatar, ScoreRing, VerifiedBadge } from "@/components/Marketplace";
import { PublicLayout } from "@/components/SiteChrome";
import { Button } from "@/components/ui/button";
import { providerBySlug, services } from "@/data/marketplace";
import { ArrowLeft, CheckCircle2, Clock3, ExternalLink, Flag, Gauge, MapPin, MessageSquareText, RefreshCw, ShieldCheck, Star } from "lucide-react";
import { Link, useRoute } from "wouter";

export default function Provider() {
  const [, params] = useRoute("/providers/:slug");
  const provider = providerBySlug(params?.slug ?? "") ?? providerBySlug("northstar-social")!;
  const providerServices = services.filter((service) => service.providerId === provider.id);
  return <PublicLayout><section className="border-b border-slate-200 bg-white"><div className="container py-10"><Button variant="ghost" asChild className="mb-6 -ms-3 text-slate-500"><Link href="/providers"><ArrowLeft className="size-4 rtl:rotate-180"/>Provider directory</Link></Button><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div className="flex items-start gap-5"><ProviderAvatar provider={provider} large/><div><div className="flex flex-wrap items-center gap-3"><h1 className="text-3xl font-extrabold tracking-tight text-slate-950 sm:text-5xl">{provider.name}</h1>{provider.verified&&<VerifiedBadge/>}</div><p className="mt-3 max-w-2xl text-slate-600">{provider.description}</p><div className="mt-4 flex flex-wrap gap-4 text-sm text-slate-500"><span className="flex items-center gap-1.5"><MapPin className="size-4"/>{provider.location}</span><span className="flex items-center gap-1.5"><Clock3 className="size-4"/>Active since {provider.since}</span><span className="flex items-center gap-1.5"><RefreshCw className="size-4"/>Updated {provider.updatedMinutes}m ago</span></div></div></div><Button asChild className="h-12 rounded-xl bg-[#0B2A68] px-6"><Link href={`/services?q=${encodeURIComponent(provider.name)}`}>Explore services<ExternalLink className="size-4"/></Link></Button></div></div></section>
    <section className="container grid gap-8 py-10 lg:grid-cols-[1fr_340px]"><div><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><p className="section-kicker">Beacon assessment</p><h2 className="mt-2 text-2xl font-extrabold text-slate-950">Why this provider earns {provider.score}</h2></div><ScoreRing score={provider.score} size="lg"/></div><div className="mt-8 grid gap-5 sm:grid-cols-3"><Signal title="Order success" value={`${provider.successRate}%`} icon={<Gauge/>} width={provider.successRate}/><Signal title="User rating" value={`${provider.rating}/5`} icon={<Star/>} width={provider.rating*20}/><Signal title="Data freshness" value={`${provider.updatedMinutes} min`} icon={<RefreshCw/>} width={94}/></div><div className="mt-7 rounded-xl bg-slate-50 p-5"><h3 className="font-bold text-slate-900">Strengths verified by ProviderBeacon</h3><div className="mt-4 flex flex-wrap gap-2">{provider.strengths.map((item) => <span key={item} className="inline-flex items-center gap-1.5 rounded-full bg-white px-3 py-2 text-xs font-semibold text-slate-700 ring-1 ring-slate-200"><CheckCircle2 className="size-3.5 text-emerald-500"/>{item}</span>)}</div></div></div>
      <div className="mt-8"><div className="flex items-end justify-between"><div><p className="section-kicker">Live catalogue</p><h2 className="mt-2 text-2xl font-extrabold text-slate-950">Available services</h2></div><span className="text-sm text-slate-500">{providerServices.length} listed</span></div><div className="mt-5 grid gap-4">{providerServices.map((service) => <article key={service.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2"><span className="platform-chip">{service.platform}</span><span className="text-xs font-medium text-slate-400">{service.quality}</span></div><h3 className="mt-3 font-extrabold text-slate-900">{service.name}</h3><p className="mt-2 text-xs text-slate-500">Start {service.startTime} · {service.refill} refill · {service.retention}% retention</p></div><div className="flex items-center justify-between gap-5 sm:block sm:text-end"><div><span className="text-2xl font-extrabold">${service.pricePerThousand.toFixed(2)}</span><p className="text-[10px] uppercase tracking-wide text-slate-400">per 1,000</p></div><Button asChild size="sm" className="mt-0 rounded-lg bg-[#0B2A68] sm:mt-3"><Link href={`/compare?services=${service.id}`}>Compare</Link></Button></div></div></article>)}</div></div></div>
      <aside className="space-y-5"><div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-emerald-500 text-white"><ShieldCheck/></div><div><p className="font-extrabold text-emerald-950">Identity verified</p><p className="text-xs text-emerald-700">Reviewed by ProviderBeacon</p></div></div><ul className="mt-5 grid gap-3 text-sm text-emerald-900"><li className="flex gap-2"><CheckCircle2 className="size-4 shrink-0"/>Business contact confirmed</li><li className="flex gap-2"><CheckCircle2 className="size-4 shrink-0"/>Service data ownership verified</li><li className="flex gap-2"><CheckCircle2 className="size-4 shrink-0"/>Support response tested</li></ul></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-extrabold text-slate-950">Provider snapshot</h2><div className="mt-5 grid gap-4"><AsideMetric icon={<MessageSquareText/>} label="Reviews" value={provider.reviews.toLocaleString()}/><AsideMetric icon={<Clock3/>} label="Response time" value={provider.responseTime}/><AsideMetric icon={<Gauge/>} label="Success rate" value={`${provider.successRate}%`}/></div></div><a href={`mailto:trust@providerbeacon.com?subject=${encodeURIComponent(`Data report: ${provider.name}`)}`} className="flex w-full items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-semibold text-slate-500 hover:bg-red-50 hover:text-red-700"><Flag className="size-4"/>Report inaccurate data</a></aside></section></PublicLayout>;
}
function Signal({title,value,icon,width}:{title:string;value:string;icon:React.ReactNode;width:number}){return <div><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-xs font-semibold text-slate-500"><span className="text-cyan-600 [&_svg]:size-4">{icon}</span>{title}</span><strong>{value}</strong></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-blue-600 to-teal-400" style={{width:`${Math.min(width,100)}%`}}/></div></div>}
function AsideMetric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="flex items-center justify-between border-b border-slate-100 pb-3 last:border-0 last:pb-0"><span className="flex items-center gap-2 text-sm text-slate-500"><span className="text-cyan-600 [&_svg]:size-4">{icon}</span>{label}</span><strong className="text-sm text-slate-900">{value}</strong></div>}
