import OfferEvidence, { serviceName, serviceScope } from "@/components/OfferEvidence";
import { formatPrice, unitLabel, pricingCopy } from "@/i18n/pricing";
import { CataloguePagination } from "@/components/CataloguePagination";
import { CatalogueState } from "@/components/CatalogueState";
import { catalogueCopy, percentLabel } from "@/i18n/catalogue";
import { ProviderAvatar, ScoreRing, VerifiedBadge } from "@/components/Marketplace";
import { PublicLayout } from "@/components/SiteChrome";
import { Button } from "@/components/ui/button";
import { copy, useLocale } from "@/contexts/LocaleContext";
import { useMarketplaceData } from "@/contexts/MarketplaceDataContext";
import { formatNumber, localizeData, localizeDuration, pageCopy } from "@/i18n/messages";
import { ArrowLeft, CheckCircle2, Clock3, ExternalLink, Flag, Gauge, MapPin, MessageSquareText, RefreshCw, ShieldCheck, Star } from "lucide-react";
import { Link, useRoute } from "wouter";

export default function Provider() {
  const { locale } = useLocale();
  const { providerBySlug, services } = useMarketplaceData();
  const t = pageCopy[locale];
  const common = copy[locale];
  const [, params] = useRoute("/providers/:slug");
  const provider = providerBySlug(params?.slug ?? "");
  if (!provider) return <PublicLayout><CatalogueState kind="providerMissing" /></PublicLayout>;
  const providerServices = services.filter(service => service.providerId === provider.id);
  return <PublicLayout>
    <section className="border-b border-slate-200 bg-white"><div className="container py-10"><Button variant="ghost" asChild className="mb-6 -ms-3 text-slate-500"><Link href="/providers"><ArrowLeft className="size-4 rtl:rotate-180"/>{common.navProviders}</Link></Button><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div className="flex items-start gap-5"><ProviderAvatar provider={provider} large/><div><div className="flex flex-wrap items-center gap-3"><h1 className="text-3xl font-extrabold tracking-tight text-slate-950 sm:text-5xl">{provider.name}</h1>{provider.verified && <VerifiedBadge/>}</div><p className="mt-3 max-w-2xl text-slate-600">{localizeData(locale, provider.description)}</p><div className="mt-4 flex flex-wrap gap-4 text-sm text-slate-500"><span className="flex items-center gap-1.5"><MapPin className="size-4"/>{localizeData(locale, provider.location)}</span><span className="flex items-center gap-1.5"><Clock3 className="size-4"/>{locale === "ar" ? "مدرج منذ" : "Listed since"} <bdi>{provider.since}</bdi></span><span className="flex items-center gap-1.5"><RefreshCw className="size-4"/>{provider.updatedMinutes == null ? catalogueCopy[locale].freshnessUnknown : `${t.updatedAgo} ${formatNumber(locale, provider.updatedMinutes)} ${t.minutesAgo}`}</span></div></div></div><Button asChild className="h-12 rounded-xl bg-[#0B2A68] px-6"><Link href={`/services?q=${encodeURIComponent(provider.name)}`}>{t.exploreServices}<ExternalLink className="size-4"/></Link></Button></div></div></section>
    {provider.apiConnected && <section className="container pt-6"><div className="rounded-xl border border-teal-200 bg-teal-50 p-5"><p className="font-bold text-teal-800">{locale === "ar" ? "كتالوج مستورد من اتصال API الفعلي" : "Catalogue imported through the connected API"}</p><p className="mt-2 text-sm leading-7 text-slate-600">{locale === "ar" ? "أسعار وخدمات من المصدر مباشرة. تظهر وحدة البيع عندما تتوفر بياناتها؛ يمكنك مراجعة مصدر كل عرض وتفاصيله. نشر الكتالوج لا يعني اعتماد جودة الخدمة." : "Prices and services directly from the provider. Sale units appear where supported by source data; each offer includes its source and details. Catalogue publication does not approve service quality."}</p></div></section>}
    <section className="container grid gap-8 py-10 lg:grid-cols-[1fr_340px]"><div><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><p className="section-kicker">{t.assessment}</p><h2 className="mt-2 text-2xl font-extrabold text-slate-950">{provider.score == null ? catalogueCopy[locale].insufficient : t.whyEarns} <bdi>{provider.score}</bdi></h2></div><ScoreRing score={provider.score} size="lg"/></div><div className="mt-8 grid gap-5 sm:grid-cols-3"><Signal title={t.orderSuccess} value={percentLabel(provider.successRate)} icon={<Gauge/>} width={provider.successRate}/><Signal title={t.userRating} value={provider.rating == null ? "—" : `${provider.rating}/5`} icon={<Star/>} width={provider.rating == null ? null : provider.rating*20}/><Signal title={t.dataFreshness} value={provider.updatedMinutes == null ? "—" : `${formatNumber(locale, provider.updatedMinutes)} ${t.minutesAgo}`} icon={<RefreshCw/>} width={null}/></div><div className="mt-7 rounded-xl bg-slate-50 p-5"><h3 className="font-bold text-slate-900">{t.providerSnapshot}</h3><div className="mt-4 flex flex-wrap gap-2">{provider.strengths.map(item => <span key={item} className="inline-flex items-center gap-1.5 rounded-full bg-white px-3 py-2 text-xs font-semibold text-slate-700 ring-1 ring-slate-200"><CheckCircle2 className="size-3.5 text-emerald-500"/>{localizeData(locale, item)}</span>)}</div></div></div>
      <div className="mt-8"><div className="flex items-end justify-between"><div><p className="section-kicker">{t.liveCatalogue}</p><h2 className="mt-2 text-2xl font-extrabold text-slate-950">{t.availableServices}</h2></div><span className="text-sm text-slate-500"><bdi>{formatNumber(locale, provider.activeServicesCount)}</bdi> {t.listed}</span></div><div className="mt-5 grid gap-4">{providerServices.map(service => <article key={service.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2"><span className="platform-chip">{service.platform}</span>{!service.billingCycle && !service.sourceUrl && <span className="text-xs font-medium text-slate-400">{localizeData(locale, service.quality)}</span>}</div><h3 className="mt-3 font-extrabold text-slate-900">{serviceName(locale, service)}</h3>{!service.billingCycle && <p className="mt-2 text-xs text-slate-500">{t.start} <bdi dir="ltr">{localizeDuration(locale, service.startTime)}</bdi> · {localizeData(locale, service.refill)} · <bdi dir="ltr">{percentLabel(service.retention)}</bdi> {t.retention}</p>}</div><div className="flex items-center justify-between gap-5 sm:block sm:text-end"><div><bdi dir="ltr" className="text-2xl font-extrabold">{formatPrice(locale, service)}</bdi><p className="text-[10px] uppercase tracking-wide text-slate-400">{unitLabel(locale, service)}</p>{service.packageDescription && <p className="mt-1 max-w-xs text-xs text-slate-500" dir="auto">{serviceScope(locale, service)}</p>}</div><Button asChild size="sm" className="mt-0 rounded-lg bg-[#0B2A68] sm:mt-3"><Link href={service.priceUnit === "package" ? `/compare?services=${service.id}` : `/services?platform=${encodeURIComponent(service.platform)}&category=${encodeURIComponent(service.category)}`}>{service.priceUnit === "package" ? common.compare : locale === "ar" ? "قارن عروضًا مشابهة" : "Compare similar offers"}</Link></Button></div></div><OfferEvidence service={service} showTerms/></article>)}</div><CataloguePagination/></div></div>
      <aside className="space-y-5"><div className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><p className="font-bold text-slate-800">{provider.verified ? catalogueCopy[locale].verificationRecorded : catalogueCopy[locale].pendingVerification}</p><p className="mt-3 text-sm text-slate-600">{catalogueCopy[locale].noScore}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-extrabold text-slate-950">{t.providerSnapshot}</h2><div className="mt-5 grid gap-4"><AsideMetric icon={<MessageSquareText/>} label={t.reviews} value={formatNumber(locale, provider.reviews)}/><AsideMetric icon={<Clock3/>} label={t.responseTime} value={localizeDuration(locale, provider.responseTime)}/><AsideMetric icon={<Gauge/>} label={t.successRate} value={percentLabel(provider.successRate)}/></div></div><a href={`mailto:trust@providerbeacon.com?subject=${encodeURIComponent(`Data report: ${provider.name}`)}`} className="flex w-full items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-semibold text-slate-500 hover:bg-red-50 hover:text-red-700"><Flag className="size-4"/>{t.reportData}</a></aside></section>
  </PublicLayout>;
}
function Signal({title,value,icon,width}:{title:string;value:string;icon:React.ReactNode;width:number|null}){return <div><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-xs font-semibold text-slate-500"><span className="text-cyan-600 [&_svg]:size-4">{icon}</span>{title}</span><bdi><strong>{value}</strong></bdi></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-blue-600 to-teal-400" style={{width:`${Math.min(width ?? 0,100)}%`}}/></div></div>}
function AsideMetric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="flex items-center justify-between border-b border-slate-100 pb-3 last:border-0 last:pb-0"><span className="flex items-center gap-2 text-sm text-slate-500"><span className="text-cyan-600 [&_svg]:size-4">{icon}</span>{label}</span><bdi><strong className="text-sm text-slate-900">{value}</strong></bdi></div>}
