import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAuthText } from "@/i18n/auth";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, Copy, KeyRound, Loader2, ShieldCheck, Smartphone } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function Security() {
  const text = useAuthText();
  const utils = trpc.useUtils();
  const summary = trpc.auth.security.summary.useQuery(undefined, { retry: false });
  const [currentPassword, setCurrentPassword] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [code, setCode] = useState("");
  const passwordMutation = trpc.auth.security.changePassword.useMutation({ onSuccess: async () => { toast.success(text("passwordChanged")); setCurrentPassword(""); setNewPassword(""); await summary.refetch(); }, onError: error => toast.error(error.message) });
  const beginMfa = trpc.auth.security.beginMfa.useMutation({ onError: error => toast.error(error.message) });
  const confirmMfa = trpc.auth.security.confirmMfa.useMutation({ onSuccess: async () => { toast.success(text("mfaEnabled")); await Promise.all([summary.refetch(), utils.admin.audit.list.invalidate()]); }, onError: error => toast.error(error.message) });
  const revoke = trpc.auth.security.revokeOtherSessions.useMutation({ onSuccess: async () => { toast.success(text("sessionsRevoked")); await summary.refetch(); }, onError: error => toast.error(error.message) });

  return <DashboardLayout><div className="mx-auto max-w-5xl p-2 sm:p-5"><div className="flex items-center gap-4 border-b border-slate-200 pb-6"><div className="grid size-12 place-items-center rounded-2xl bg-emerald-50 text-emerald-700"><ShieldCheck/></div><div><h1 className="text-3xl font-extrabold text-slate-950">{text("security")}</h1><p className="mt-1 text-sm text-slate-500">{text("securityBody")}</p></div></div>
    {summary.isLoading ? <Loader2 className="mx-auto my-16 size-7 animate-spin"/> : !summary.data?.localAccount ? <div className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-6 text-amber-900">{text("localRequired")}</div> : <div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2 font-extrabold text-slate-950"><KeyRound className="size-5 text-blue-700"/>{text("changePassword")}</div><Badge variant="outline">{text("lastPasswordChange")}: {summary.data.passwordChangedAt ? new Date(summary.data.passwordChangedAt).toLocaleDateString() : "—"}</Badge></div><form className="mt-5 grid gap-4" onSubmit={event => { event.preventDefault(); passwordMutation.mutate({ currentPassword, newPassword }); }}><label className="grid gap-2 text-sm font-semibold text-slate-700">{text("currentPassword")}<Input dir="ltr" type="password" autoComplete="current-password" value={currentPassword} onChange={event => setCurrentPassword(event.target.value)} required/></label><label className="grid gap-2 text-sm font-semibold text-slate-700">{text("newPassword")}<Input dir="ltr" type="password" autoComplete="new-password" value={newPassword} onChange={event => setNewPassword(event.target.value)} required/></label><p className="text-xs leading-5 text-slate-500">{text("passwordRule")}</p><Button disabled={passwordMutation.isPending}>{passwordMutation.isPending && <Loader2 className="size-4 animate-spin"/>}{text("changePassword")}</Button></form></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2 font-extrabold text-slate-950"><Smartphone className="size-5 text-beacon-700"/>{text("mfa")}</div><Badge className={summary.data.mfaEnabled ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}>{summary.data.mfaEnabled ? text("mfaEnabled") : text("mfaDisabled")}</Badge></div>{!summary.data.mfaEnabled && !beginMfa.data && <Button className="mt-6 w-full" variant="outline" onClick={() => beginMfa.mutate()} disabled={beginMfa.isPending}>{beginMfa.isPending && <Loader2 className="size-4 animate-spin"/>}{text("setupMfa")}</Button>}{beginMfa.data && !confirmMfa.data && <div className="mt-6"><p className="text-sm leading-6 text-slate-500">{text("scanQr")}</p><img src={beginMfa.data.qrDataUrl} alt="TOTP setup QR code" className="mx-auto my-5 size-[220px] rounded-xl border border-slate-200"/><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-bold text-slate-500">{text("manualSecret")}</p><div className="mt-2 flex gap-2"><code dir="ltr" className="min-w-0 flex-1 break-all rounded-lg bg-white p-2 text-xs">{beginMfa.data.secret}</code><Button size="icon" variant="outline" onClick={() => navigator.clipboard.writeText(beginMfa.data!.secret)}><Copy className="size-4"/></Button></div></div><form className="mt-4 flex gap-2" onSubmit={event => { event.preventDefault(); confirmMfa.mutate({ code }); }}><Input dir="ltr" inputMode="numeric" autoComplete="one-time-code" value={code} onChange={event => setCode(event.target.value)} placeholder="123456" required/><Button disabled={confirmMfa.isPending}>{confirmMfa.isPending && <Loader2 className="size-4 animate-spin"/>}{text("confirmMfa")}</Button></form></div>}{confirmMfa.data && <div className="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><div className="flex items-center gap-2 font-extrabold text-emerald-900"><CheckCircle2 className="size-5"/>{text("recoveryCodes")}</div><p className="mt-2 text-sm text-emerald-800">{text("recoveryBody")}</p><div dir="ltr" className="mt-4 grid grid-cols-2 gap-2 font-mono text-sm">{confirmMfa.data.recoveryCodes.map(item => <code key={item} className="rounded-lg bg-white p-2 text-center">{item}</code>)}</div></div>}</section>
      <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-2"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-extrabold text-slate-950">{text("activeSessions")}: {summary.data.activeSessions}</h2><p className="mt-1 text-sm text-slate-500">{text("sessionsRevoked")}</p></div><Button variant="outline" onClick={() => revoke.mutate()} disabled={revoke.isPending}>{revoke.isPending && <Loader2 className="size-4 animate-spin"/>}{text("revokeSessions")}</Button></div></section></div>}
  </div></DashboardLayout>;
}
