import { useLocale, type Locale } from "@/contexts/LocaleContext";

import { reviewEn, reviewAr } from "./review";
import { syncEn, syncAr } from "./sync";

const en = {
  ...reviewEn,
  ...syncEn,
  searchServices: "Search services", searchServicesHint: "Service, provider, category or ID", allStatuses: "All statuses", platform: "Platform", allPlatforms: "All platforms", rowsPerPage: "Rows per page", refresh: "Refresh", matchingServices: "Matching services", publicationHint: "Reviewed offers require approval. An enabled API source catalogue may also show pending imported records with their original rates.", providerNotPublished: "Provider is not published", loadError: "Data could not be loaded.", retry: "Retry", loading: "Loading…", noServices: "No services match these filters.", pagination: "Pagination", page: "Page", previous: "Previous", next: "Next", editService: "Edit service", saveChanges: "Save changes",

  controlCenter:"Beacon Control Center", overview:"Overview", providers:"Providers", services:"Services", team:"Team & access", translations:"Translations", audit:"Audit log", integrations:"Credential vault", security:"Account security", signOut:"Sign out", menu:"Menu", toggleNavigation:"Toggle navigation",
  providerOperations:"Provider operations", providerSubtitle:"Verification, risk state and ownership", serviceCatalogue:"Service catalogue", serviceSubtitle:"Pricing freshness, classification and publishing", teamTitle:"Team & access", teamSubtitle:"Server-enforced roles, permissions and account status", translationTitle:"Translation workspace", translationSubtitle:"Review status across five supported markets", auditTitle:"Audit log", auditSubtitle:"Immutable record of administrative actions",
  provider:"Provider", status:"Status", beaconScore:"Beacon score", success:"Success", lastUpdate:"Last update", service:"Service", price:"Price / 1K", quality:"Quality", publishing:"Publishing", member:"Member", role:"Role", accessStatus:"Access status", added:"Added", time:"Time (local)", action:"Action", resource:"Resource", summary:"Summary",
  draft:"Draft", pendingReview:"Pending review", active:"Active", suspended:"Suspended", paused:"Paused", archived:"Archived", published:"Published",
  inviteTitle:"Invite with least privilege", inviteBody:"The selected role is enforced by the server on every protected operation.", inviteMember:"Invite member", invitationRecorded:"Invitation recorded", inviteLink:"Secure invitation link", copyLink:"Copy link", noInvites:"No team invitations yet. Add only the people who need operational access.", noTeamPermission:"You do not have permission to view the team directory.", noAuditPermission:"You do not have permission to view the audit log.", noAudit:"No administrative actions have been recorded.", providerUpdated:"Provider status updated", serviceUpdated:"Service updated",
  owner:"Owner", administrator:"Administrator", operationsManager:"Operations Manager", providerReviewer:"Provider Reviewer", catalogueEditor:"Catalogue Editor", translationManager:"Translation Manager", auditor:"Read-only Auditor",
  language:"Language", coverage:"Coverage", reviewState:"Review state", source:"Source", humanReviewed:"Human reviewed", reviewRequired:"Review required",
  signInContinue:"Sign in to continue", adminNotConfigured:"Admin access is not configured", authRequired:"Access to this dashboard requires authentication. Continue to launch the login flow.", authSetup:"The public marketplace is available, but staff authentication must be configured before the control center can be used.", signIn:"Sign in", accessRestricted:"Access restricted", accessBody:"Your account does not have permission to open the control center. Contact an authorized administrator if your role has changed.", returnHome:"Return to ProviderBeacon",
  operationsOverview:"Operations overview", overviewBody:"Provider integrity, catalogue freshness, team access and audit activity in one protected workspace.", systemsOperational:"All systems operational", verifiedProviders:"Verified providers", publishedServices:"Published services", teamMembers:"Team members", recordedActions:"Recorded actions", manageProviders:"Manage providers", manageServices:"Manage services", manageTeam:"Manage team access", reviewAudit:"Review audit log",
  entityType:"Entity type", entityId:"Entity ID", fieldName:"Field name", locale:"Language", translationValue:"Translated value", saveTranslation:"Save translation", translationSaved:"Translation saved", noTranslations:"No reviewed translations have been saved yet.", machineTranslated:"Machine translated", reviewed:"Reviewed",
  aiAnalysis:"AI risk analysis", analyze:"Analyze", aiAdvisory:"Advisory only — a human reviewer must make the final decision.", confidence:"Confidence", recommendedAction:"Recommended action", riskLevel:"Risk level", signals:"Evidence signals",
  importServices:"Import provider services", providerApiUrl:"Provider SMM API URL", apiKey:"API key", syncNow:"Sync now", apiKeyNotStored:"The API key is used once for this manual sync and is not stored in the database.", importedServices:"Services imported",
  integrationTitle:"Encrypted credential vault", integrationSubtitle:"Store provider keys with AES-256-GCM and control scheduled imports.", vaultBody:"Secrets are encrypted before database storage and are never returned to the browser.", integrationName:"Integration name", syncInterval:"Sync interval", enabled:"Enabled", disabled:"Disabled", saveCredential:"Save encrypted integration", credentialHint:"Stored key", scheduledSync:"Scheduled sync", lastSync:"Last sync", nextSync:"Next sync", noIntegrations:"No provider integrations are configured.", everyHour:"Every hour", every6Hours:"Every 6 hours", every12Hours:"Every 12 hours", everyDay:"Every day", everyWeek:"Every week", integrationSaved:"Encrypted integration saved", integrationUpdated:"Integration updated", keyOptional:"Leave blank to keep the stored key.", never:"Never",
  connectProvider:"Connect a provider", connectProviderBody:"Save the connection disabled, test it manually, then enable the schedule after the imported catalogue is reviewed.", stepProvider:"Choose the provider", stepProviderBody:"Link the API to the correct marketplace profile.", stepCredential:"Store the credential", stepCredentialBody:"The key is encrypted immediately and is never returned to the browser.", stepVerify:"Test before scheduling", stepVerifyBody:"Run one manual sync, review prices, then enable automatic updates.", selectProvider:"Select a provider", selectProviderFirst:"Choose a provider from the list before saving or testing.", addNewProvider:"Add a new provider", providerName:"Provider name", providerWebsite:"Provider website", createProvider:"Create provider draft", providerDraftCreated:"Provider draft created and selected", demoProvider:"Demo data", integrationNameExample:"Example: Provider production API", endpointHelp:"Enter the provider's API endpoint, not its dashboard or homepage.", apiKeyPlaceholder:"Paste the provider API key", keyEncryptedHelp:"Encrypted with AES-256-GCM before database storage.", enableAfterTest:"Recommended: keep disabled until the first manual sync succeeds.", updateIntegration:"Update integration", cancelEdit:"Cancel edit", saveAndTest:"Save and test now", connectedProviders:"Connected providers", connectedProvidersBody:"Each security, scheduling and activity signal has its own column for faster review.", credential:"Credential", schedule:"Schedule", activity:"Activity", actions:"Actions", syncError:"Sync error", failures:"Failures", edit:"Edit", delete:"Delete", deleteIntegrationConfirm:"Delete this disabled integration and its encrypted credential?", integrationDeleted:"Integration deleted",
  suspendMember:"Suspend", reactivateMember:"Reactivate", memberUpdated:"Team access updated", suspendMemberConfirm:"Suspend this account and revoke all active sessions?",
} as const;

export type AdminTextKey = keyof typeof en;
const translations: Record<Exclude<Locale,"en">, Partial<Record<AdminTextKey,string>>> = {
  ar: {
    ...reviewAr,
    ...syncAr,
    searchServices: "البحث في الخدمات", searchServicesHint: "اسم الخدمة أو المزود أو التصنيف أو المعرّف", allStatuses: "جميع الحالات", platform: "المنصة", allPlatforms: "جميع المنصات", rowsPerPage: "صفوف في الصفحة", refresh: "تحديث", matchingServices: "الخدمات المطابقة", publicationHint: "العروض المعتمدة تتطلب مراجعة. كتالوج API المفعّل يعرض أيضًا سجلات المصدر المستوردة بأسعارها الأصلية مع بقاء حالة مراجعتها واضحة.", providerNotPublished: "المزود غير منشور", loadError: "تعذّر تحميل البيانات.", retry: "إعادة المحاولة", loading: "جارٍ التحميل…", noServices: "لا توجد خدمات تطابق هذه الفلاتر.", pagination: "التنقل بين الصفحات", page: "الصفحة", previous: "السابق", next: "التالي", editService: "تعديل الخدمة", saveChanges: "حفظ التعديلات",

    controlCenter:"مركز تحكم Beacon", overview:"نظرة عامة", providers:"المزودون", services:"الخدمات", team:"الفريق والصلاحيات", translations:"الترجمات", audit:"سجل التدقيق", integrations:"خزنة المفاتيح", security:"أمان الحساب", signOut:"تسجيل الخروج", menu:"القائمة", toggleNavigation:"تبديل التنقل",
    providerOperations:"عمليات المزودين", providerSubtitle:"التوثيق وحالة المخاطر والملكية", serviceCatalogue:"دليل الخدمات", serviceSubtitle:"حداثة الأسعار والتصنيف والنشر", teamTitle:"الفريق والصلاحيات", teamSubtitle:"أدوار وصلاحيات وحالة حساب يفرضها الخادم", translationTitle:"مساحة عمل الترجمة", translationSubtitle:"حالة المراجعة في الأسواق الخمسة المدعومة", auditTitle:"سجل التدقيق", auditSubtitle:"سجل ثابت للإجراءات الإدارية",
    provider:"المزود", status:"الحالة", beaconScore:"درجة Beacon", success:"النجاح", lastUpdate:"آخر تحديث", service:"الخدمة", price:"السعر / ١٬٠٠٠", quality:"الجودة", publishing:"النشر", member:"العضو", role:"الدور", accessStatus:"حالة الوصول", added:"تاريخ الإضافة", time:"الوقت المحلي", action:"الإجراء", resource:"المورد", summary:"الملخص",
    draft:"مسودة", pendingReview:"بانتظار المراجعة", active:"نشط", suspended:"موقوف", paused:"متوقف مؤقتًا", archived:"مؤرشف", published:"منشور",
    inviteTitle:"دعوة بأقل قدر من الصلاحيات", inviteBody:"يفرض الخادم الدور المحدد على كل عملية محمية.", inviteMember:"دعوة عضو", invitationRecorded:"تم تسجيل الدعوة", inviteLink:"رابط الدعوة الآمن", copyLink:"نسخ الرابط", noInvites:"لا توجد دعوات بعد. أضف فقط من يحتاج إلى وصول تشغيلي.", noTeamPermission:"ليست لديك صلاحية لعرض دليل الفريق.", noAuditPermission:"ليست لديك صلاحية لعرض سجل التدقيق.", noAudit:"لم تُسجّل أي إجراءات إدارية.", providerUpdated:"تم تحديث حالة المزود", serviceUpdated:"تم تحديث الخدمة",
    owner:"المالك", administrator:"المسؤول", operationsManager:"مدير العمليات", providerReviewer:"مراجع المزودين", catalogueEditor:"محرر الدليل", translationManager:"مدير الترجمة", auditor:"مدقق للقراءة فقط",
    language:"اللغة", coverage:"التغطية", reviewState:"حالة المراجعة", source:"المصدر", humanReviewed:"مراجعة بشرية", reviewRequired:"تحتاج إلى مراجعة",
    signInContinue:"سجّل الدخول للمتابعة", adminNotConfigured:"وصول الإدارة غير مهيأ", authRequired:"تتطلب لوحة الإدارة مصادقة. تابع لبدء تسجيل الدخول.", authSetup:"السوق العام متاح، لكن يجب إعداد مصادقة الموظفين قبل استخدام مركز التحكم.", signIn:"تسجيل الدخول", accessRestricted:"الوصول مقيّد", accessBody:"لا يملك حسابك صلاحية فتح مركز التحكم. تواصل مع مسؤول معتمد إذا تغير دورك.", returnHome:"العودة إلى ProviderBeacon",
    operationsOverview:"نظرة عامة على العمليات", overviewBody:"سلامة المزودين وحداثة الدليل وصلاحيات الفريق وسجل النشاط في مساحة محمية واحدة.", systemsOperational:"جميع الأنظمة تعمل", verifiedProviders:"مزودون موثّقون", publishedServices:"خدمات منشورة", teamMembers:"أعضاء الفريق", recordedActions:"إجراءات مسجلة", manageProviders:"إدارة المزودين", manageServices:"إدارة الخدمات", manageTeam:"إدارة صلاحيات الفريق", reviewAudit:"مراجعة سجل التدقيق",
    entityType:"نوع العنصر", entityId:"معرّف العنصر", fieldName:"اسم الحقل", locale:"اللغة", translationValue:"النص المترجم", saveTranslation:"حفظ الترجمة", translationSaved:"تم حفظ الترجمة", noTranslations:"لم تُحفظ ترجمات مراجعة بعد.", machineTranslated:"مترجمة آليًا", reviewed:"تمت مراجعتها",
    aiAnalysis:"تحليل المخاطر بالذكاء الاصطناعي", analyze:"تحليل", aiAdvisory:"استشاري فقط — يجب أن يتخذ المراجع البشري القرار النهائي.", confidence:"الثقة", recommendedAction:"الإجراء المقترح", riskLevel:"مستوى المخاطر", signals:"إشارات الأدلة",
    importServices:"استيراد خدمات المزود", providerApiUrl:"رابط SMM API للمزود", apiKey:"مفتاح API", syncNow:"مزامنة الآن", apiKeyNotStored:"يُستخدم مفتاح API مرة واحدة لهذه المزامنة اليدوية ولا يُحفظ في قاعدة البيانات.", importedServices:"الخدمات المستوردة",
    integrationTitle:"خزنة المفاتيح المشفرة", integrationSubtitle:"احفظ مفاتيح المزودين بتشفير AES-256-GCM وتحكم بالمزامنة المجدولة.", vaultBody:"تُشفّر الأسرار قبل حفظها في قاعدة البيانات ولا تعاد إلى المتصفح مطلقًا.", integrationName:"اسم التكامل", syncInterval:"فترة المزامنة", enabled:"مفعّل", disabled:"معطل", saveCredential:"حفظ التكامل المشفر", credentialHint:"المفتاح المحفوظ", scheduledSync:"المزامنة المجدولة", lastSync:"آخر مزامنة", nextSync:"المزامنة التالية", noIntegrations:"لا توجد تكاملات مزودين مهيأة.", everyHour:"كل ساعة", every6Hours:"كل 6 ساعات", every12Hours:"كل 12 ساعة", everyDay:"كل يوم", everyWeek:"كل أسبوع", integrationSaved:"تم حفظ التكامل المشفر", integrationUpdated:"تم تحديث التكامل", keyOptional:"اتركه فارغًا للاحتفاظ بالمفتاح المحفوظ.", never:"أبدًا",
    connectProvider:"ربط مزود", connectProviderBody:"احفظ الاتصال معطلاً، اختبره يدويًا، ثم فعّل الجدولة بعد مراجعة الدليل المستورد.", stepProvider:"اختر المزود", stepProviderBody:"اربط API بملف المزود الصحيح في السوق.", stepCredential:"احفظ المفتاح", stepCredentialBody:"يُشفّر المفتاح فورًا ولا يُعاد إلى المتصفح.", stepVerify:"اختبر قبل الجدولة", stepVerifyBody:"نفّذ مزامنة يدوية، راجع الأسعار، ثم فعّل التحديث التلقائي.", selectProvider:"اختر مزودًا", selectProviderFirst:"اختر مزودًا من القائمة قبل الحفظ أو الاختبار.", addNewProvider:"إضافة مزود جديد", providerName:"اسم المزود", providerWebsite:"موقع المزود", createProvider:"إنشاء مسودة المزود", providerDraftCreated:"تم إنشاء مسودة المزود واختيارها", demoProvider:"بيانات تجريبية", integrationNameExample:"مثال: API الإنتاج للمزود", endpointHelp:"أدخل رابط API الخاص بالمزود، وليس لوحة التحكم أو الصفحة الرئيسية.", apiKeyPlaceholder:"ألصق مفتاح API للمزود", keyEncryptedHelp:"يُشفّر بـ AES-256-GCM قبل التخزين في قاعدة البيانات.", enableAfterTest:"الموصى به: اتركها معطلة حتى تنجح أول مزامنة يدوية.", updateIntegration:"تحديث التكامل", cancelEdit:"إلغاء التعديل", saveAndTest:"حفظ واختبار الآن", connectedProviders:"المزودون المرتبطون", connectedProvidersBody:"لكل إشارة أمن وجدولة ونشاط عمود مستقل لتسهيل المراجعة.", credential:"المفتاح", schedule:"الجدولة", activity:"النشاط", actions:"الإجراءات", syncError:"خطأ مزامنة", failures:"مرات الفشل", edit:"تعديل", delete:"حذف", deleteIntegrationConfirm:"حذف هذا التكامل المعطل ومفتاحه المشفر؟", integrationDeleted:"تم حذف التكامل",
    suspendMember:"إيقاف", reactivateMember:"إعادة التفعيل", memberUpdated:"تم تحديث وصول العضو", suspendMemberConfirm:"إيقاف هذا الحساب وإلغاء جميع جلساته النشطة؟",
  },
  es: { controlCenter:"Centro de control Beacon", overview:"Resumen", providers:"Proveedores", services:"Servicios", team:"Equipo y acceso", translations:"Traducciones", audit:"Registro de auditoría", signOut:"Cerrar sesión", providerOperations:"Operaciones de proveedores", serviceCatalogue:"Catálogo de servicios", teamTitle:"Equipo y acceso", translationTitle:"Espacio de traducción", auditTitle:"Registro de auditoría", provider:"Proveedor", status:"Estado", service:"Servicio", price:"Precio / 1.000", quality:"Calidad", member:"Miembro", role:"Rol", active:"Activo", suspended:"Suspendido", inviteTitle:"Invitar con privilegios mínimos", inviteMember:"Invitar miembro", language:"Idioma", coverage:"Cobertura", reviewState:"Estado de revisión" },
  hi: { controlCenter:"Beacon नियंत्रण केंद्र", overview:"अवलोकन", providers:"प्रदाता", services:"सेवाएँ", team:"टीम और पहुँच", translations:"अनुवाद", audit:"ऑडिट लॉग", signOut:"साइन आउट", providerOperations:"प्रदाता संचालन", serviceCatalogue:"सेवा कैटलॉग", teamTitle:"टीम और पहुँच", translationTitle:"अनुवाद कार्यक्षेत्र", auditTitle:"ऑडिट लॉग", provider:"प्रदाता", status:"स्थिति", service:"सेवा", price:"कीमत / 1,000", quality:"गुणवत्ता", member:"सदस्य", role:"भूमिका", active:"सक्रिय", suspended:"निलंबित", inviteTitle:"न्यूनतम अधिकार के साथ आमंत्रित करें", inviteMember:"सदस्य आमंत्रित करें", language:"भाषा", coverage:"कवरेज", reviewState:"समीक्षा स्थिति" },
  zh: { controlCenter:"Beacon 控制中心", overview:"概览", providers:"服务商", services:"服务", team:"团队与权限", translations:"翻译", audit:"审计日志", signOut:"退出登录", providerOperations:"服务商运营", serviceCatalogue:"服务目录", teamTitle:"团队与权限", translationTitle:"翻译工作区", auditTitle:"审计日志", provider:"服务商", status:"状态", service:"服务", price:"价格 / 1,000", quality:"质量", member:"成员", role:"角色", active:"启用", suspended:"停用", inviteTitle:"按最小权限邀请", inviteMember:"邀请成员", language:"语言", coverage:"覆盖率", reviewState:"审核状态" },
};

export function useAdminText() {
  const { locale } = useLocale();
  return (key: AdminTextKey) => locale === "en" ? en[key] : translations[locale][key] ?? en[key];
}
