import { useLocale, type Locale } from "@/contexts/LocaleContext";

const en = {
  signIn:"Staff sign in", signInBody:"Use your ProviderBeacon team email and password.", email:"Email address", password:"Password", continue:"Continue", verificationCode:"Verification code", verify:"Verify and sign in", mfaBody:"Enter the six-digit code from your authenticator app or a recovery code.", oauthFallback:"Use legacy OAuth", invalid:"Unable to sign in", backHome:"Back to marketplace",
  setup:"Create owner account", setupBody:"This one-time setup creates the first independent administrator.", setupToken:"One-time setup token", name:"Full name", confirmPassword:"Confirm password", createAccount:"Create secure account", setupUnavailable:"The owner account has already been created.", passwordRule:"At least 14 characters with uppercase, lowercase, number and symbol.", mismatch:"Passwords do not match.",
  invitedTitle:"Create your team account", invitedBody:"Use the exact email address that received this invitation.", createInvited:"Create account and join team",
  security:"Account security", securityBody:"Manage your password, multi-factor authentication and active sessions.", passwordChanged:"Password updated and other sessions revoked.", currentPassword:"Current password", newPassword:"New password", changePassword:"Change password", mfa:"Authenticator app", mfaEnabled:"MFA is enabled", mfaDisabled:"MFA is not enabled", setupMfa:"Set up MFA", scanQr:"Scan this QR code with your authenticator app, then enter a code to confirm.", manualSecret:"Manual setup key", confirmMfa:"Confirm and enable MFA", recoveryCodes:"Recovery codes", recoveryBody:"Store these codes offline. Each code works once and will not be shown again.", revokeSessions:"Revoke other sessions", sessionsRevoked:"Other sessions revoked", localRequired:"This feature requires an independent staff account.", activeSessions:"Active sessions", lastPasswordChange:"Last password change",
};
export type AuthTextKey = keyof typeof en;
const translations: Record<Exclude<Locale,"en">, Partial<Record<AuthTextKey,string>>> = {
  ar: { signIn:"دخول فريق العمل", signInBody:"استخدم بريد فريق ProviderBeacon وكلمة المرور.", email:"البريد الإلكتروني", password:"كلمة المرور", continue:"متابعة", verificationCode:"رمز التحقق", verify:"تحقق وسجّل الدخول", mfaBody:"أدخل الرمز المؤلف من ستة أرقام من تطبيق المصادقة أو رمز استرداد.", oauthFallback:"استخدام تسجيل الدخول القديم", invalid:"تعذر تسجيل الدخول", backHome:"العودة إلى السوق", setup:"إنشاء حساب المالك", setupBody:"إعداد لمرة واحدة ينشئ أول مسؤول مستقل.", setupToken:"رمز الإعداد لمرة واحدة", name:"الاسم الكامل", confirmPassword:"تأكيد كلمة المرور", createAccount:"إنشاء حساب آمن", setupUnavailable:"تم إنشاء حساب المالك مسبقًا.", passwordRule:"14 محرفًا على الأقل مع حرف كبير وصغير ورقم ورمز.", mismatch:"كلمتا المرور غير متطابقتين.", invitedTitle:"إنشاء حساب الفريق", invitedBody:"استخدم البريد نفسه الذي استلم الدعوة.", createInvited:"إنشاء الحساب والانضمام", security:"أمان الحساب", securityBody:"إدارة كلمة المرور والمصادقة متعددة العوامل والجلسات.", passwordChanged:"تم تحديث كلمة المرور وإلغاء الجلسات الأخرى.", currentPassword:"كلمة المرور الحالية", newPassword:"كلمة المرور الجديدة", changePassword:"تغيير كلمة المرور", mfa:"تطبيق المصادقة", mfaEnabled:"المصادقة الثنائية مفعلة", mfaDisabled:"المصادقة الثنائية غير مفعلة", setupMfa:"إعداد المصادقة الثنائية", scanQr:"امسح رمز QR بتطبيق المصادقة ثم أدخل رمزًا للتأكيد.", manualSecret:"مفتاح الإعداد اليدوي", confirmMfa:"تأكيد وتفعيل MFA", recoveryCodes:"رموز الاسترداد", recoveryBody:"احفظ هذه الرموز دون اتصال. كل رمز يعمل مرة واحدة ولن يظهر مجددًا.", revokeSessions:"إلغاء الجلسات الأخرى", sessionsRevoked:"تم إلغاء الجلسات الأخرى", localRequired:"تتطلب هذه الميزة حساب فريق مستقلًا.", activeSessions:"الجلسات النشطة", lastPasswordChange:"آخر تغيير لكلمة المرور" },
  es: { signIn:"Acceso del equipo", signInBody:"Usa tu correo y contraseña de ProviderBeacon.", email:"Correo electrónico", password:"Contraseña", continue:"Continuar", verificationCode:"Código de verificación", verify:"Verificar e ingresar", mfaBody:"Ingresa el código de seis dígitos o un código de recuperación.", backHome:"Volver al mercado", setup:"Crear cuenta del propietario", setupToken:"Token de configuración", name:"Nombre completo", confirmPassword:"Confirmar contraseña", createAccount:"Crear cuenta segura", security:"Seguridad de la cuenta", currentPassword:"Contraseña actual", newPassword:"Nueva contraseña", changePassword:"Cambiar contraseña", setupMfa:"Configurar MFA", revokeSessions:"Revocar otras sesiones" },
  hi: { signIn:"टीम साइन इन", signInBody:"अपना ProviderBeacon टीम ईमेल और पासवर्ड उपयोग करें।", email:"ईमेल पता", password:"पासवर्ड", continue:"जारी रखें", verificationCode:"सत्यापन कोड", verify:"सत्यापित करके साइन इन करें", mfaBody:"ऑथेंटिकेटर का छह अंकों का कोड या रिकवरी कोड दर्ज करें।", backHome:"मार्केटप्लेस पर वापस", setup:"मालिक खाता बनाएँ", setupToken:"एक बार का सेटअप टोकन", name:"पूरा नाम", confirmPassword:"पासवर्ड की पुष्टि", createAccount:"सुरक्षित खाता बनाएँ", security:"खाता सुरक्षा", currentPassword:"वर्तमान पासवर्ड", newPassword:"नया पासवर्ड", changePassword:"पासवर्ड बदलें", setupMfa:"MFA सेट करें", revokeSessions:"अन्य सत्र रद्द करें" },
  zh: { signIn:"团队登录", signInBody:"使用 ProviderBeacon 团队邮箱和密码。", email:"电子邮箱", password:"密码", continue:"继续", verificationCode:"验证码", verify:"验证并登录", mfaBody:"输入身份验证器的六位代码或恢复代码。", backHome:"返回市场", setup:"创建所有者账户", setupToken:"一次性设置令牌", name:"姓名", confirmPassword:"确认密码", createAccount:"创建安全账户", security:"账户安全", currentPassword:"当前密码", newPassword:"新密码", changePassword:"更改密码", setupMfa:"设置 MFA", revokeSessions:"撤销其他会话" },
};

export function useAuthText() {
  const { locale } = useLocale();
  return (key: AuthTextKey) => locale === "en" ? en[key] : translations[locale][key] ?? en[key];
}
