import type { Locale } from "@/contexts/LocaleContext";

const en = {
  loading: "Loading the catalogue…", empty: "No published services yet", emptyBody: "Provider profiles and services will appear after editorial review.",
  unavailable: "The catalogue is temporarily unavailable. Please try again.", retry: "Try again", demo: "Demo catalogue — fictional providers, prices and scores for preview only.",
  insufficient: "Insufficient evidence", unknown: "Not available", pendingVerification: "Identity not verified", verificationRecorded: "Provider verification recorded",
  comparisonEmpty: "Select at least two available services to compare.", comparisonMissing: "Some selected services are no longer available. Return to services to update your comparison.",
  featuredService: "Catalogue selection", latestCatalogue: "Published catalogue", noScore: "A Beacon Score will appear once enough verified evidence is available.",
  freshnessUnknown: "Update date unavailable", providerMissing: "This provider is not available.",
};
export const catalogueCopy: Record<Locale, typeof en> = {
  en,
  ar: { loading: "جارٍ تحميل الدليل…", empty: "لا توجد خدمات منشورة بعد", emptyBody: "ستظهر ملفات المزودين والخدمات بعد المراجعة التحريرية.", unavailable: "الدليل غير متاح مؤقتًا. يرجى المحاولة مجددًا.", retry: "إعادة المحاولة", demo: "دليل تجريبي — المزودون والأسعار والدرجات افتراضية للمعاينة فقط.", insufficient: "أدلة غير كافية", unknown: "غير متاح", pendingVerification: "الهوية غير موثّقة", verificationRecorded: "تم تسجيل توثيق المزود", comparisonEmpty: "اختر خدمتين متاحتين على الأقل للمقارنة.", comparisonMissing: "بعض الخدمات المختارة لم تعد متاحة. ارجع إلى الخدمات لتحديث المقارنة.", featuredService: "خدمة من الدليل", latestCatalogue: "الدليل المنشور", noScore: "ستظهر درجة Beacon عند توفر أدلة موثّقة كافية.", freshnessUnknown: "تاريخ التحديث غير متاح", providerMissing: "هذا المزود غير متاح." },
  es: { loading: "Cargando el catálogo…", empty: "Todavía no hay servicios publicados", emptyBody: "Los perfiles y servicios aparecerán después de la revisión editorial.", unavailable: "El catálogo no está disponible temporalmente. Inténtalo de nuevo.", retry: "Reintentar", demo: "Catálogo de demostración: proveedores, precios y puntuaciones ficticios.", insufficient: "Evidencia insuficiente", unknown: "No disponible", pendingVerification: "Identidad no verificada", verificationRecorded: "Verificación del proveedor registrada", comparisonEmpty: "Selecciona al menos dos servicios disponibles para comparar.", comparisonMissing: "Algunos servicios seleccionados ya no están disponibles. Actualiza la comparación desde el catálogo.", featuredService: "Selección del catálogo", latestCatalogue: "Catálogo publicado", noScore: "Beacon Score aparecerá cuando haya suficiente evidencia verificada.", freshnessUnknown: "Fecha de actualización no disponible", providerMissing: "Este proveedor no está disponible." },
  hi: { loading: "सूची लोड हो रही है…", empty: "अभी कोई प्रकाशित सेवा नहीं है", emptyBody: "संपादकीय समीक्षा के बाद प्रदाता और सेवाएँ दिखाई देंगी।", unavailable: "सूची अभी उपलब्ध नहीं है। कृपया फिर प्रयास करें।", retry: "फिर प्रयास करें", demo: "डेमो सूची — प्रदाता, कीमतें और स्कोर केवल पूर्वावलोकन के लिए काल्पनिक हैं।", insufficient: "अपर्याप्त प्रमाण", unknown: "उपलब्ध नहीं", pendingVerification: "पहचान सत्यापित नहीं है", verificationRecorded: "प्रदाता सत्यापन दर्ज है", comparisonEmpty: "तुलना के लिए कम से कम दो उपलब्ध सेवाएँ चुनें।", comparisonMissing: "कुछ चुनी गई सेवाएँ अब उपलब्ध नहीं हैं। सूची से तुलना अपडेट करें।", featuredService: "सूची से चयन", latestCatalogue: "प्रकाशित सूची", noScore: "पर्याप्त सत्यापित प्रमाण मिलने पर Beacon Score दिखेगा।", freshnessUnknown: "अपडेट की तारीख उपलब्ध नहीं है", providerMissing: "यह प्रदाता उपलब्ध नहीं है।" },
  zh: { loading: "正在加载目录…", empty: "暂无已发布的服务", emptyBody: "服务商资料和服务将在编辑审核后显示。", unavailable: "目录暂时不可用，请重试。", retry: "重试", demo: "演示目录：服务商、价格和评分均为虚构，仅供预览。", insufficient: "证据不足", unknown: "暂无数据", pendingVerification: "身份尚未验证", verificationRecorded: "已记录服务商验证", comparisonEmpty: "请至少选择两项可用服务进行比较。", comparisonMissing: "部分所选服务已不可用，请返回目录更新比较。", featuredService: "目录精选", latestCatalogue: "已发布目录", noScore: "获得足够的已验证证据后将显示 Beacon Score。", freshnessUnknown: "暂无更新日期", providerMissing: "此服务商不可用。" },
};
export const percentLabel = (value: number | null) => value == null ? "—" : `${value}%`;
