import type { Locale } from "@/contexts/LocaleContext";

const en = {
  skipMain: "Skip to main content", primaryNav: "Primary navigation", mobileNav: "Mobile navigation", account: "Account",
  footerTagline: "Independent provider intelligence for clearer, safer and more transparent service decisions.", footerPlatform: "Platform", footerForProviders: "For providers", footerCompany: "Company", trustScores: "Trust scores", claimProfile: "Claim profile", getVerified: "Get verified", partnerStandards: "Partner standards", providerApi: "Provider API", about: "About", editorialPolicy: "Editorial policy", contact: "Contact", rights: "All rights reserved.", transparentRanking: "Transparent ranking · No hidden placement",
  verified: "Verified", since: "Since", rating: "Rating", success: "Success", response: "Response", score: "Score", providerBy: "by", price: "Price", perThousand: "per 1,000", start: "Start", retention: "Retention", refill: "Refill", delivery: "Delivery", quality: "Quality", service: "Service", provider: "Provider", protection: "Protection",
  popular: "Popular:", aiRecommendation: "AI recommendation", bestOverallMatch: "Best overall match", liveData: "Live data", whyAi: "Why Beacon AI chose it", reasonReliable: "Highest reliability in this price range", reasonRefill: "30-day refill protection", reasonFresh: "Price verified recently", smartDiscovery: "Smart discovery", providerIntelligence: "Provider intelligence", verifiedPricing: "Verified pricing", verifiedPricingBody: "Rate history and freshness signals make stale offers visible.", operationalReliability: "Operational reliability", operationalReliabilityBody: "Completion, support and retention signals shape every score.", independentRanking: "Independent ranking", independentRankingBody: "Sponsored placements never alter the core reliability score.", forProviders: "For service providers", earnTrust: "Earn trust before asking for the click.", earnTrustBody: "Claim your profile, verify your business and keep your service data accurate.", claimProvider: "Claim your provider profile",
  servicesEyebrow: "Provider intelligence marketplace", servicesTitle: "Discover services with evidence, not guesswork.", servicesBody: "Search verified service data, compare providers side-by-side and see exactly what drives each Beacon Score.", searchCatalogue: "Search service catalogue", searchServices: "Search by platform, service, provider or category", allPlatforms: "All platforms", recommended: "Recommended", lowestPrice: "Lowest price", bestRetention: "Best retention", moreFilters: "More filters", allQuality: "All quality levels", refillOnly: "Refill protection only", resetFilters: "Reset filters", servicesFound: "services found", updatedContinuously: "Updated continuously", noMatches: "No exact matches yet", noMatchesBody: "Try another platform or broader keyword.", readyCompare: "Ready to compare", clearComparison: "Clear comparison", addToComparison: "Add to comparison", removeFromComparison: "Remove from comparison",
  providersEyebrow: "Provider directory", providersTitle: "Know who you are buying from.", providersBody: "Independent profiles combine verification, service history, user feedback and operational signals.", searchProviders: "Search provider or market", evaluatedProfiles: "Evaluated profiles", providersFound: "providers found", identityRanking: "Identity-aware ranking", onboarding: "Provider onboarding", buildProfile: "Build a profile buyers can verify.", onboardingBody: "Claim your provider profile and submit business details for an independent trust review.", startVerification: "Start verification",
  backServices: "Back to services", compareEyebrow: "Beacon Compare", compareTitle: "Compare the signals that matter.", compareBody: "Price is only the beginning. Compare reliability, protection, retention and delivery side-by-side.", selectedServices: "services selected", comparison: "Comparison", serviceSignals: "Service signals", bestOverallScore: "Best overall score", beaconScore: "Beacon Score", excellent: "Excellent", explainableScore: "Explainable score", pricePerThousand: "Price / 1,000", startDelivery: "Start & delivery", refillProtection: "Refill protection", providerPolicy: "Provider-backed policy", orderRange: "Order range", chooseConfidence: "Choose with confidence.", viewProvider: "View provider",
  activeSince: "Active since", updatedAgo: "Updated", minutesAgo: "min ago", exploreServices: "Explore services", assessment: "Beacon assessment", whyEarns: "Why this provider earns", orderSuccess: "Order success", userRating: "User rating", dataFreshness: "Data freshness", strengthsVerified: "Strengths verified by ProviderBeacon", liveCatalogue: "Live catalogue", availableServices: "Available services", listed: "listed", identityVerified: "Identity verified", reviewedBy: "Reviewed by ProviderBeacon", businessContact: "Business contact confirmed", dataOwnership: "Service data ownership verified", supportTested: "Support response tested", providerSnapshot: "Provider snapshot", reviews: "Reviews", responseTime: "Response time", successRate: "Success rate", reportData: "Report inaccurate data",
  notFound: "Page not found", notFoundBody: "Sorry, the page you are looking for does not exist. It may have been moved or deleted.", goHome: "Go home",
};

type PageMessages = typeof en;

const ar: PageMessages = {
  skipMain: "انتقل إلى المحتوى الرئيسي", primaryNav: "التنقل الرئيسي", mobileNav: "تنقل الهاتف", account: "الحساب",
  footerTagline: "معلومات مستقلة عن المزودين لاتخاذ قرارات خدمات أوضح وأكثر أمانًا وشفافية.", footerPlatform: "المنصة", footerForProviders: "للمزودين", footerCompany: "الشركة", trustScores: "درجات الثقة", claimProfile: "المطالبة بالملف", getVerified: "احصل على التوثيق", partnerStandards: "معايير الشركاء", providerApi: "واجهة المزودين", about: "من نحن", editorialPolicy: "سياسة التحرير", contact: "تواصل معنا", rights: "جميع الحقوق محفوظة.", transparentRanking: "ترتيب شفاف · لا مواضع مخفية",
  verified: "موثّق", since: "منذ", rating: "التقييم", success: "النجاح", response: "الاستجابة", score: "الدرجة", providerBy: "من", price: "السعر", perThousand: "لكل 1,000", start: "البدء", retention: "الاستبقاء", refill: "الضمان", delivery: "التسليم", quality: "الجودة", service: "الخدمة", provider: "المزود", protection: "الحماية",
  popular: "الأكثر طلبًا:", aiRecommendation: "توصية الذكاء الاصطناعي", bestOverallMatch: "أفضل خيار إجمالًا", liveData: "بيانات مباشرة", whyAi: "لماذا اختاره Beacon AI", reasonReliable: "أعلى موثوقية ضمن هذه الفئة السعرية", reasonRefill: "ضمان تعويض لمدة 30 يومًا", reasonFresh: "تم التحقق من السعر مؤخرًا", smartDiscovery: "اكتشاف ذكي", providerIntelligence: "معلومات المزودين", verifiedPricing: "أسعار متحقق منها", verifiedPricingBody: "يكشف سجل الأسعار ومؤشرات الحداثة العروض القديمة.", operationalReliability: "الموثوقية التشغيلية", operationalReliabilityBody: "تدخل نسب الإنجاز والدعم والاستبقاء في كل درجة.", independentRanking: "ترتيب مستقل", independentRankingBody: "الإعلانات المدفوعة لا تغيّر درجة الموثوقية الأساسية.", forProviders: "لمزودي الخدمات", earnTrust: "ابنِ الثقة قبل أن تطلب النقرة.", earnTrustBody: "طالب بملفك ووثّق نشاطك وحافظ على دقة بيانات خدماتك.", claimProvider: "طالب بملف مزودك",
  servicesEyebrow: "سوق معلومات المزودين", servicesTitle: "اكتشف الخدمات بالدليل، لا بالتخمين.", servicesBody: "ابحث في بيانات خدمات متحقق منها، وقارن المزودين جنبًا إلى جنب، وافهم أسباب كل درجة Beacon.", searchCatalogue: "البحث في دليل الخدمات", searchServices: "ابحث بالمنصة أو الخدمة أو المزود أو الفئة", allPlatforms: "كل المنصات", recommended: "الموصى به", lowestPrice: "الأقل سعرًا", bestRetention: "أفضل استبقاء", moreFilters: "فلاتر إضافية", allQuality: "كل مستويات الجودة", refillOnly: "الخدمات ذات الضمان فقط", resetFilters: "إعادة ضبط الفلاتر", servicesFound: "خدمة موجودة", updatedContinuously: "تحديث مستمر", noMatches: "لا توجد نتائج مطابقة", noMatchesBody: "جرّب منصة أخرى أو كلمات أوسع.", readyCompare: "جاهز للمقارنة", clearComparison: "مسح المقارنة", addToComparison: "أضف إلى المقارنة", removeFromComparison: "احذف من المقارنة",
  providersEyebrow: "دليل المزودين", providersTitle: "اعرف ممن تشتري.", providersBody: "تجمع الملفات المستقلة بين التوثيق وسجل الخدمات وآراء المستخدمين والمؤشرات التشغيلية.", searchProviders: "ابحث عن مزود أو سوق", evaluatedProfiles: "ملفات خضعت للتقييم", providersFound: "مزودون", identityRanking: "ترتيب يراعي التحقق من الهوية", onboarding: "انضمام المزودين", buildProfile: "أنشئ ملفًا يستطيع المشترون التحقق منه.", onboardingBody: "طالب بملف مزودك وقدّم بيانات النشاط لمراجعة ثقة مستقلة.", startVerification: "ابدأ التوثيق",
  backServices: "العودة إلى الخدمات", compareEyebrow: "مقارنة Beacon", compareTitle: "قارن الإشارات المهمة فعلًا.", compareBody: "السعر مجرد البداية. قارن الموثوقية والحماية والاستبقاء وسرعة التسليم جنبًا إلى جنب.", selectedServices: "خدمات محددة", comparison: "المقارنة", serviceSignals: "مؤشرات الخدمة", bestOverallScore: "أفضل درجة إجمالية", beaconScore: "درجة Beacon", excellent: "ممتاز", explainableScore: "درجة قابلة للتفسير", pricePerThousand: "السعر لكل 1,000", startDelivery: "البدء والتسليم", refillProtection: "ضمان التعويض", providerPolicy: "سياسة يضمنها المزود", orderRange: "نطاق الطلب", chooseConfidence: "اختر بثقة.", viewProvider: "عرض المزود",
  activeSince: "نشط منذ", updatedAgo: "آخر تحديث", minutesAgo: "دقيقة مضت", exploreServices: "استكشف الخدمات", assessment: "تقييم Beacon", whyEarns: "لماذا استحق هذا المزود", orderSuccess: "نجاح الطلبات", userRating: "تقييم المستخدمين", dataFreshness: "حداثة البيانات", strengthsVerified: "نقاط قوة تحققت منها ProviderBeacon", liveCatalogue: "دليل مباشر", availableServices: "الخدمات المتاحة", listed: "مدرجة", identityVerified: "الهوية موثّقة", reviewedBy: "تمت المراجعة بواسطة ProviderBeacon", businessContact: "تم تأكيد جهة اتصال النشاط", dataOwnership: "تم التحقق من ملكية بيانات الخدمات", supportTested: "تم اختبار استجابة الدعم", providerSnapshot: "ملخص المزود", reviews: "المراجعات", responseTime: "وقت الاستجابة", successRate: "نسبة النجاح", reportData: "الإبلاغ عن بيانات غير دقيقة",
  notFound: "الصفحة غير موجودة", notFoundBody: "عذرًا، الصفحة التي تبحث عنها غير موجودة وقد تكون نُقلت أو حُذفت.", goHome: "العودة للرئيسية",
};

const es: PageMessages = {
  ...en,
  skipMain: "Ir al contenido principal", primaryNav: "Navegación principal", mobileNav: "Navegación móvil", account: "Cuenta", footerTagline: "Inteligencia independiente de proveedores para decisiones más claras, seguras y transparentes.", footerPlatform: "Plataforma", footerForProviders: "Para proveedores", footerCompany: "Empresa", trustScores: "Puntuaciones de confianza", claimProfile: "Reclamar perfil", getVerified: "Verificarse", partnerStandards: "Normas para socios", providerApi: "API de proveedores", about: "Nosotros", editorialPolicy: "Política editorial", contact: "Contacto", rights: "Todos los derechos reservados.", transparentRanking: "Clasificación transparente · Sin posiciones ocultas",
  verified: "Verificado", since: "Desde", rating: "Valoración", success: "Éxito", response: "Respuesta", score: "Puntuación", providerBy: "por", price: "Precio", perThousand: "por 1.000", start: "Inicio", retention: "Retención", refill: "Reposición", delivery: "Entrega", quality: "Calidad", service: "Servicio", provider: "Proveedor", protection: "Protección",
  popular: "Popular:", aiRecommendation: "Recomendación de IA", bestOverallMatch: "Mejor opción general", liveData: "Datos en vivo", whyAi: "Por qué Beacon AI lo eligió", reasonReliable: "Mayor fiabilidad en este rango de precio", reasonRefill: "Protección de reposición por 30 días", reasonFresh: "Precio verificado recientemente", smartDiscovery: "Descubrimiento inteligente", providerIntelligence: "Inteligencia de proveedores", verifiedPricing: "Precios verificados", verifiedPricingBody: "El historial y la frescura hacen visibles las ofertas obsoletas.", operationalReliability: "Fiabilidad operativa", operationalReliabilityBody: "Finalización, soporte y retención determinan cada puntuación.", independentRanking: "Clasificación independiente", independentRankingBody: "Los espacios patrocinados no alteran la puntuación base.", forProviders: "Para proveedores de servicios", earnTrust: "Genera confianza antes de pedir el clic.", earnTrustBody: "Reclama tu perfil, verifica tu negocio y mantén tus datos actualizados.", claimProvider: "Reclamar perfil de proveedor",
  servicesEyebrow: "Mercado de inteligencia de proveedores", servicesTitle: "Descubre servicios con evidencia, no con suposiciones.", servicesBody: "Busca datos verificados, compara proveedores y entiende cada Beacon Score.", searchCatalogue: "Buscar en el catálogo", searchServices: "Buscar por plataforma, servicio, proveedor o categoría", allPlatforms: "Todas las plataformas", recommended: "Recomendados", lowestPrice: "Menor precio", bestRetention: "Mejor retención", moreFilters: "Más filtros", allQuality: "Todos los niveles", refillOnly: "Solo con reposición", resetFilters: "Restablecer filtros", servicesFound: "servicios encontrados", updatedContinuously: "Actualización continua", noMatches: "No hay coincidencias exactas", noMatchesBody: "Prueba otra plataforma o términos más amplios.", readyCompare: "Listo para comparar", clearComparison: "Limpiar comparación", addToComparison: "Añadir a la comparación", removeFromComparison: "Quitar de la comparación",
  providersEyebrow: "Directorio de proveedores", providersTitle: "Conoce a quién le compras.", providersBody: "Perfiles independientes con verificación, historial, opiniones y señales operativas.", searchProviders: "Buscar proveedor o mercado", evaluatedProfiles: "Perfiles evaluados", providersFound: "proveedores encontrados", identityRanking: "Clasificación con identidad verificada", onboarding: "Incorporación de proveedores", buildProfile: "Crea un perfil que los compradores puedan verificar.", onboardingBody: "Reclama tu perfil y envía los datos del negocio para una revisión independiente.", startVerification: "Iniciar verificación",
  backServices: "Volver a servicios", compareEyebrow: "Comparador Beacon", compareTitle: "Compara las señales que importan.", compareBody: "El precio es solo el comienzo. Compara fiabilidad, protección, retención y entrega.", selectedServices: "servicios seleccionados", comparison: "Comparación", serviceSignals: "Señales del servicio", bestOverallScore: "Mejor puntuación general", beaconScore: "Puntuación Beacon", excellent: "Excelente", explainableScore: "Puntuación explicable", pricePerThousand: "Precio / 1.000", startDelivery: "Inicio y entrega", refillProtection: "Protección de reposición", providerPolicy: "Política respaldada por el proveedor", orderRange: "Rango de pedido", chooseConfidence: "Elige con confianza.", viewProvider: "Ver proveedor",
  activeSince: "Activo desde", updatedAgo: "Actualizado hace", minutesAgo: "min", exploreServices: "Explorar servicios", assessment: "Evaluación Beacon", whyEarns: "Por qué este proveedor obtiene", orderSuccess: "Éxito de pedidos", userRating: "Valoración de usuarios", dataFreshness: "Frescura de datos", strengthsVerified: "Fortalezas verificadas por ProviderBeacon", liveCatalogue: "Catálogo en vivo", availableServices: "Servicios disponibles", listed: "publicados", identityVerified: "Identidad verificada", reviewedBy: "Revisado por ProviderBeacon", businessContact: "Contacto comercial confirmado", dataOwnership: "Propiedad de datos verificada", supportTested: "Respuesta de soporte probada", providerSnapshot: "Resumen del proveedor", reviews: "Reseñas", responseTime: "Tiempo de respuesta", successRate: "Tasa de éxito", reportData: "Reportar datos incorrectos",
  notFound: "Página no encontrada", notFoundBody: "La página que buscas no existe; puede haber sido movida o eliminada.", goHome: "Ir al inicio",
};

const hi: PageMessages = {
  ...en,
  skipMain: "मुख्य सामग्री पर जाएँ", primaryNav: "मुख्य नेविगेशन", mobileNav: "मोबाइल नेविगेशन", account: "खाता", footerTagline: "स्पष्ट, सुरक्षित और पारदर्शी सेवा निर्णयों के लिए स्वतंत्र प्रदाता इंटेलिजेंस।", footerPlatform: "प्लेटफ़ॉर्म", footerForProviders: "प्रदाताओं के लिए", footerCompany: "कंपनी", trustScores: "विश्वास स्कोर", claimProfile: "प्रोफ़ाइल का दावा करें", getVerified: "सत्यापन पाएँ", partnerStandards: "भागीदार मानक", providerApi: "प्रदाता API", about: "हमारे बारे में", editorialPolicy: "संपादकीय नीति", contact: "संपर्क", rights: "सर्वाधिकार सुरक्षित।", transparentRanking: "पारदर्शी रैंकिंग · कोई छिपा स्थान नहीं",
  verified: "सत्यापित", since: "से", rating: "रेटिंग", success: "सफलता", response: "प्रतिक्रिया", score: "स्कोर", providerBy: "द्वारा", price: "कीमत", perThousand: "प्रति 1,000", start: "शुरुआत", retention: "रिटेंशन", refill: "रीफिल", delivery: "डिलीवरी", quality: "गुणवत्ता", service: "सेवा", provider: "प्रदाता", protection: "सुरक्षा",
  popular: "लोकप्रिय:", aiRecommendation: "AI सुझाव", bestOverallMatch: "सर्वश्रेष्ठ विकल्प", liveData: "लाइव डेटा", whyAi: "Beacon AI ने इसे क्यों चुना", reasonReliable: "इस कीमत में सबसे अधिक विश्वसनीयता", reasonRefill: "30-दिन रीफिल सुरक्षा", reasonFresh: "कीमत हाल ही में सत्यापित", smartDiscovery: "स्मार्ट खोज", providerIntelligence: "प्रदाता इंटेलिजेंस", verifiedPricing: "सत्यापित कीमतें", verifiedPricingBody: "कीमत इतिहास पुराने ऑफ़र को स्पष्ट करता है।", operationalReliability: "परिचालन विश्वसनीयता", operationalReliabilityBody: "पूर्णता, सहायता और रिटेंशन हर स्कोर बनाते हैं।", independentRanking: "स्वतंत्र रैंकिंग", independentRankingBody: "प्रायोजित स्थान मूल स्कोर नहीं बदलते।", forProviders: "सेवा प्रदाताओं के लिए", earnTrust: "क्लिक माँगने से पहले भरोसा बनाएँ।", earnTrustBody: "अपनी प्रोफ़ाइल का दावा करें और सेवा डेटा सटीक रखें।", claimProvider: "प्रदाता प्रोफ़ाइल का दावा करें",
  servicesEyebrow: "प्रदाता इंटेलिजेंस मार्केटप्लेस", servicesTitle: "अनुमान नहीं, प्रमाण के साथ सेवाएँ खोजें।", servicesBody: "सत्यापित डेटा खोजें, प्रदाताओं की तुलना करें और हर Beacon Score समझें।", searchCatalogue: "सेवा सूची खोजें", searchServices: "प्लेटफ़ॉर्म, सेवा, प्रदाता या श्रेणी से खोजें", allPlatforms: "सभी प्लेटफ़ॉर्म", recommended: "सुझाए गए", lowestPrice: "सबसे कम कीमत", bestRetention: "सर्वश्रेष्ठ रिटेंशन", moreFilters: "अधिक फ़िल्टर", allQuality: "सभी गुणवत्ता स्तर", refillOnly: "केवल रीफिल सुरक्षा", resetFilters: "फ़िल्टर रीसेट करें", servicesFound: "सेवाएँ मिलीं", updatedContinuously: "लगातार अपडेट", noMatches: "कोई सटीक परिणाम नहीं", noMatchesBody: "दूसरा प्लेटफ़ॉर्म या व्यापक शब्द आज़माएँ।", readyCompare: "तुलना के लिए तैयार", clearComparison: "तुलना साफ़ करें", addToComparison: "तुलना में जोड़ें", removeFromComparison: "तुलना से हटाएँ",
  providersEyebrow: "प्रदाता निर्देशिका", providersTitle: "जानें कि आप किससे खरीद रहे हैं।", providersBody: "स्वतंत्र प्रोफ़ाइल सत्यापन, सेवा इतिहास, प्रतिक्रिया और परिचालन संकेत जोड़ती हैं।", searchProviders: "प्रदाता या बाज़ार खोजें", evaluatedProfiles: "मूल्यांकित प्रोफ़ाइल", providersFound: "प्रदाता मिले", identityRanking: "पहचान-आधारित रैंकिंग", onboarding: "प्रदाता ऑनबोर्डिंग", buildProfile: "खरीदारों के सत्यापन योग्य प्रोफ़ाइल बनाएँ।", onboardingBody: "अपनी प्रोफ़ाइल का दावा करें और स्वतंत्र समीक्षा के लिए व्यावसायिक विवरण भेजें।", startVerification: "सत्यापन शुरू करें",
  backServices: "सेवाओं पर वापस जाएँ", compareEyebrow: "Beacon तुलना", compareTitle: "महत्वपूर्ण संकेतों की तुलना करें।", compareBody: "कीमत केवल शुरुआत है। विश्वसनीयता, सुरक्षा, रिटेंशन और डिलीवरी की साथ-साथ तुलना करें।", selectedServices: "सेवाएँ चुनी गईं", comparison: "तुलना", serviceSignals: "सेवा संकेत", bestOverallScore: "सर्वश्रेष्ठ कुल स्कोर", beaconScore: "Beacon स्कोर", excellent: "उत्कृष्ट", explainableScore: "समझने योग्य स्कोर", pricePerThousand: "कीमत / 1,000", startDelivery: "शुरुआत और डिलीवरी", refillProtection: "रीफिल सुरक्षा", providerPolicy: "प्रदाता समर्थित नीति", orderRange: "ऑर्डर सीमा", chooseConfidence: "विश्वास से चुनें।", viewProvider: "प्रदाता देखें",
  activeSince: "तब से सक्रिय", updatedAgo: "अपडेट", minutesAgo: "मिनट पहले", exploreServices: "सेवाएँ देखें", assessment: "Beacon मूल्यांकन", whyEarns: "इस प्रदाता का स्कोर", orderSuccess: "ऑर्डर सफलता", userRating: "उपयोगकर्ता रेटिंग", dataFreshness: "डेटा ताज़गी", strengthsVerified: "ProviderBeacon द्वारा सत्यापित खूबियाँ", liveCatalogue: "लाइव सूची", availableServices: "उपलब्ध सेवाएँ", listed: "सूचीबद्ध", identityVerified: "पहचान सत्यापित", reviewedBy: "ProviderBeacon द्वारा समीक्षा", businessContact: "व्यावसायिक संपर्क पुष्ट", dataOwnership: "सेवा डेटा स्वामित्व सत्यापित", supportTested: "सहायता प्रतिक्रिया जाँची गई", providerSnapshot: "प्रदाता सारांश", reviews: "समीक्षाएँ", responseTime: "प्रतिक्रिया समय", successRate: "सफलता दर", reportData: "गलत डेटा रिपोर्ट करें",
  notFound: "पेज नहीं मिला", notFoundBody: "जिस पेज को आप खोज रहे हैं वह मौजूद नहीं है; वह हटाया या स्थानांतरित किया गया हो सकता है।", goHome: "होम जाएँ",
};

const zh: PageMessages = {
  ...en,
  skipMain: "跳至主要内容", primaryNav: "主导航", mobileNav: "移动导航", account: "账户", footerTagline: "独立的服务商情报，让服务决策更清晰、更安全、更透明。", footerPlatform: "平台", footerForProviders: "服务商专区", footerCompany: "公司", trustScores: "信任评分", claimProfile: "认领资料", getVerified: "申请认证", partnerStandards: "合作标准", providerApi: "服务商 API", about: "关于我们", editorialPolicy: "编辑政策", contact: "联系我们", rights: "版权所有。", transparentRanking: "透明排名 · 无隐藏位置",
  verified: "已认证", since: "始于", rating: "评分", success: "成功率", response: "响应", score: "得分", providerBy: "服务商", price: "价格", perThousand: "每 1,000", start: "开始", retention: "留存", refill: "补充保障", delivery: "交付", quality: "质量", service: "服务", provider: "服务商", protection: "保障",
  popular: "热门：", aiRecommendation: "AI 推荐", bestOverallMatch: "综合最佳", liveData: "实时数据", whyAi: "Beacon AI 选择它的原因", reasonReliable: "该价格区间可靠性最高", reasonRefill: "30 天补充保障", reasonFresh: "价格近期已核验", smartDiscovery: "智能发现", providerIntelligence: "服务商情报", verifiedPricing: "已核验价格", verifiedPricingBody: "价格历史和新鲜度信号可识别过期报价。", operationalReliability: "运营可靠性", operationalReliabilityBody: "完成率、支持和留存共同形成评分。", independentRanking: "独立排名", independentRankingBody: "赞助位置不会改变核心可靠性评分。", forProviders: "服务商专区", earnTrust: "先建立信任，再获得点击。", earnTrustBody: "认领资料、验证企业并保持服务数据准确。", claimProvider: "认领服务商资料",
  servicesEyebrow: "服务商情报市场", servicesTitle: "用证据发现服务，而不是猜测。", servicesBody: "搜索已验证的服务数据，并排比较服务商，了解每个 Beacon Score 的依据。", searchCatalogue: "搜索服务目录", searchServices: "按平台、服务、服务商或类别搜索", allPlatforms: "所有平台", recommended: "推荐", lowestPrice: "最低价格", bestRetention: "最佳留存", moreFilters: "更多筛选", allQuality: "所有质量等级", refillOnly: "仅补充保障", resetFilters: "重置筛选", servicesFound: "项服务", updatedContinuously: "持续更新", noMatches: "暂无完全匹配", noMatchesBody: "请尝试其他平台或更宽泛的关键词。", readyCompare: "可以比较", clearComparison: "清除比较", addToComparison: "加入比较", removeFromComparison: "移出比较",
  providersEyebrow: "服务商目录", providersTitle: "了解你的交易对象。", providersBody: "独立资料汇总认证、服务历史、用户反馈和运营信号。", searchProviders: "搜索服务商或市场", evaluatedProfiles: "已评估资料", providersFound: "家服务商", identityRanking: "身份感知排名", onboarding: "服务商入驻", buildProfile: "建立买家可验证的资料。", onboardingBody: "认领服务商资料并提交企业信息，接受独立信任审核。", startVerification: "开始认证",
  backServices: "返回服务", compareEyebrow: "Beacon 比较", compareTitle: "比较真正重要的信号。", compareBody: "价格只是开始。并排比较可靠性、保障、留存和交付。", selectedServices: "项服务已选择", comparison: "比较", serviceSignals: "服务信号", bestOverallScore: "最佳综合评分", beaconScore: "Beacon 评分", excellent: "优秀", explainableScore: "可解释评分", pricePerThousand: "每 1,000 价格", startDelivery: "开始与交付", refillProtection: "补充保障", providerPolicy: "服务商保障政策", orderRange: "订单范围", chooseConfidence: "放心选择。", viewProvider: "查看服务商",
  activeSince: "活跃始于", updatedAgo: "更新于", minutesAgo: "分钟前", exploreServices: "浏览服务", assessment: "Beacon 评估", whyEarns: "该服务商为何获得", orderSuccess: "订单成功率", userRating: "用户评分", dataFreshness: "数据新鲜度", strengthsVerified: "ProviderBeacon 已核验优势", liveCatalogue: "实时目录", availableServices: "可用服务", listed: "项已上架", identityVerified: "身份已认证", reviewedBy: "由 ProviderBeacon 审核", businessContact: "企业联系方式已确认", dataOwnership: "服务数据所有权已验证", supportTested: "支持响应已测试", providerSnapshot: "服务商概览", reviews: "评价", responseTime: "响应时间", successRate: "成功率", reportData: "报告不准确数据",
  notFound: "页面未找到", notFoundBody: "抱歉，您查找的页面不存在，可能已被移动或删除。", goHome: "返回首页",
};

export const pageCopy: Record<Locale, PageMessages> = { en, es, ar, hi, zh };

const exactData: Partial<Record<Locale, Record<string, string>>> = {
  ar: {
    "Instagram Followers — Premium": "متابعو إنستغرام — ممتازة", "Instagram Followers — High Retention": "متابعو إنستغرام — استبقاء مرتفع", "Instagram Followers — Value": "متابعو إنستغرام — اقتصادية", "TikTok Views — Instant": "مشاهدات تيك توك — فورية", "TikTok Followers — Refill": "متابعو تيك توك — مع ضمان", "YouTube Views — Worldwide": "مشاهدات يوتيوب — عالمية", "Facebook Page Likes — Global": "إعجابات صفحات فيسبوك — عالمية", "Telegram Members — Stable": "أعضاء تيليغرام — ثابتون", "YouTube Subscribers — Gradual": "مشتركو يوتيوب — تدريجي", "Instagram Likes — Fast": "إعجابات إنستغرام — سريعة",
    Followers: "متابعون", Views: "مشاهدات", Likes: "إعجابات", Subscribers: "مشتركون", Members: "أعضاء", "Page likes": "إعجابات الصفحة", Standard: "قياسية", Premium: "ممتازة", Elite: "نخبة", "No refill": "دون ضمان", "30 days": "30 يومًا", "15 days": "15 يومًا", Canada: "كندا", "United Kingdom": "المملكة المتحدة", Singapore: "سنغافورة", Spain: "إسبانيا", "Fast start": "بدء سريع", "30-day refill": "ضمان 30 يومًا", "Responsive support": "دعم سريع الاستجابة", "Agency ready": "مناسب للوكالات", "Large capacity": "سعة كبيرة", "Clear tracking": "تتبع واضح", "Best value": "أفضل قيمة", "Multi-platform": "متعدد المنصات", "Stable rates": "أسعار مستقرة", "Low minimum": "حد أدنى منخفض", "Creator plans": "خطط للمبدعين", "Flexible quantities": "كميات مرنة",
  },
  es: { Followers: "Seguidores", Views: "Visualizaciones", Likes: "Me gusta", Subscribers: "Suscriptores", Members: "Miembros", "Page likes": "Me gusta de página", Standard: "Estándar", Premium: "Premium", Elite: "Élite", "No refill": "Sin reposición", "30 days": "30 días", "15 days": "15 días", Canada: "Canadá", "United Kingdom": "Reino Unido", Singapore: "Singapur", Spain: "España" },
  hi: { Followers: "फ़ॉलोअर्स", Views: "व्यूज़", Likes: "लाइक्स", Subscribers: "सब्सक्राइबर", Members: "सदस्य", "Page likes": "पेज लाइक्स", Standard: "मानक", Premium: "प्रीमियम", Elite: "एलीट", "No refill": "रीफिल नहीं", "30 days": "30 दिन", "15 days": "15 दिन" },
  zh: { Followers: "粉丝", Views: "播放量", Likes: "点赞", Subscribers: "订阅者", Members: "成员", "Page likes": "主页点赞", Standard: "标准", Premium: "高级", Elite: "精英", "No refill": "无补充", "30 days": "30 天", "15 days": "15 天", Canada: "加拿大", "United Kingdom": "英国", Singapore: "新加坡", Spain: "西班牙" },
};

Object.assign(exactData.es!, {
  "Instagram Followers — Premium": "Seguidores de Instagram — Premium", "Instagram Followers — High Retention": "Seguidores de Instagram — Alta retención", "Instagram Followers — Value": "Seguidores de Instagram — Económico", "TikTok Views — Instant": "Visualizaciones de TikTok — Instantáneas", "TikTok Followers — Refill": "Seguidores de TikTok — Con reposición", "YouTube Views — Worldwide": "Visualizaciones de YouTube — Mundial", "Facebook Page Likes — Global": "Me gusta de Facebook — Global", "Telegram Members — Stable": "Miembros de Telegram — Estables", "YouTube Subscribers — Gradual": "Suscriptores de YouTube — Gradual", "Instagram Likes — Fast": "Me gusta de Instagram — Rápidos",
  "High-retention social growth services with transparent delivery estimates and fast support.": "Servicios de crecimiento social de alta retención con plazos transparentes y soporte rápido.", "Performance-focused services for agencies that need stable capacity and detailed order tracking.": "Servicios orientados al rendimiento para agencias que necesitan capacidad estable y seguimiento detallado.", "A broad multi-platform catalogue with competitive pricing and consistent delivery windows.": "Un catálogo multiplataforma amplio con precios competitivos y plazos consistentes.", "Flexible social promotion packages for creators and small teams with entry-level budgets.": "Paquetes flexibles para creadores y equipos pequeños con presupuestos iniciales."
});
Object.assign(exactData.hi!, {
  "Instagram Followers — Premium": "Instagram फ़ॉलोअर्स — प्रीमियम", "Instagram Followers — High Retention": "Instagram फ़ॉलोअर्स — उच्च रिटेंशन", "Instagram Followers — Value": "Instagram फ़ॉलोअर्स — किफ़ायती", "TikTok Views — Instant": "TikTok व्यूज़ — तुरंत", "TikTok Followers — Refill": "TikTok फ़ॉलोअर्स — रीफिल सहित", "YouTube Views — Worldwide": "YouTube व्यूज़ — विश्वव्यापी", "Facebook Page Likes — Global": "Facebook पेज लाइक्स — वैश्विक", "Telegram Members — Stable": "Telegram सदस्य — स्थिर", "YouTube Subscribers — Gradual": "YouTube सब्सक्राइबर — क्रमिक", "Instagram Likes — Fast": "Instagram लाइक्स — तेज़",
  Canada: "कनाडा", "United Kingdom": "यूनाइटेड किंगडम", Singapore: "सिंगापुर", Spain: "स्पेन", "High-retention social growth services with transparent delivery estimates and fast support.": "पारदर्शी डिलीवरी समय और तेज़ सहायता वाली उच्च-रिटेंशन सेवाएँ।", "Performance-focused services for agencies that need stable capacity and detailed order tracking.": "स्थिर क्षमता और विस्तृत ऑर्डर ट्रैकिंग चाहने वाली एजेंसियों के लिए सेवाएँ।", "A broad multi-platform catalogue with competitive pricing and consistent delivery windows.": "प्रतिस्पर्धी कीमतों और स्थिर डिलीवरी समय वाली बहु-प्लेटफ़ॉर्म सूची।", "Flexible social promotion packages for creators and small teams with entry-level budgets.": "क्रिएटर्स और छोटी टीमों के लिए लचीले प्रचार पैकेज।"
});
Object.assign(exactData.zh!, {
  "Instagram Followers — Premium": "Instagram 粉丝 — 高级", "Instagram Followers — High Retention": "Instagram 粉丝 — 高留存", "Instagram Followers — Value": "Instagram 粉丝 — 高性价比", "TikTok Views — Instant": "TikTok 播放量 — 即时", "TikTok Followers — Refill": "TikTok 粉丝 — 含补充", "YouTube Views — Worldwide": "YouTube 播放量 — 全球", "Facebook Page Likes — Global": "Facebook 主页点赞 — 全球", "Telegram Members — Stable": "Telegram 成员 — 稳定", "YouTube Subscribers — Gradual": "YouTube 订阅者 — 渐进", "Instagram Likes — Fast": "Instagram 点赞 — 快速",
  "High-retention social growth services with transparent delivery estimates and fast support.": "高留存社交增长服务，交付时间透明，支持响应快速。", "Performance-focused services for agencies that need stable capacity and detailed order tracking.": "面向需要稳定容量和详细订单跟踪的代理机构。", "A broad multi-platform catalogue with competitive pricing and consistent delivery windows.": "广泛的多平台目录，价格有竞争力，交付时间稳定。", "Flexible social promotion packages for creators and small teams with entry-level budgets.": "适合创作者和小团队的灵活推广套餐。"
});
Object.assign(exactData.ar!, {
  "High-retention social growth services with transparent delivery estimates and fast support.": "خدمات نمو اجتماعي باستبقاء مرتفع ومواعيد تسليم واضحة ودعم سريع.", "Performance-focused services for agencies that need stable capacity and detailed order tracking.": "خدمات موجهة للأداء للوكالات التي تحتاج سعة مستقرة وتتبعًا مفصلًا للطلبات.", "A broad multi-platform catalogue with competitive pricing and consistent delivery windows.": "دليل واسع متعدد المنصات بأسعار تنافسية ومواعيد تسليم مستقرة.", "Flexible social promotion packages for creators and small teams with entry-level budgets.": "باقات ترويج مرنة للمبدعين والفرق الصغيرة بميزانيات مبدئية."
});

export function localizeData(locale: Locale, value: string) {
  return exactData[locale]?.[value] ?? value;
}

export function formatNumber(locale: Locale, value: number) {
  return new Intl.NumberFormat(locale === "zh" ? "zh-CN" : locale).format(value);
}

export function localizeDuration(locale: Locale, value: string) {
  if (locale === "en") return value;
  const units: Record<Exclude<Locale, "en">, Record<string, string>> = {
    ar: { min: "دقيقة", hours: "ساعات", hour: "ساعة", days: "أيام", day: "يوم" },
    es: { min: "min", hours: "horas", hour: "hora", days: "días", day: "día" },
    hi: { min: "मिनट", hours: "घंटे", hour: "घंटा", days: "दिन", day: "दिन" },
    zh: { min: "分钟", hours: "小时", hour: "小时", days: "天", day: "天" },
  };
  return value.replace(/\b(min|hours?|days?)\b/g, unit => units[locale][unit] ?? unit);
}
