import OfferEvidence, { serviceName, serviceScope, serviceTerms } from "./OfferEvidence";
import { formatPrice, unitLabel, pricingCopy } from "@/i18n/pricing";
import { useMarketplaceData } from "@/contexts/MarketplaceDataContext";
import { catalogueCopy, percentLabel } from "@/i18n/catalogue";
import { Button } from "@/components/ui/button";
import { copy, useLocale } from "@/contexts/LocaleContext";
import { platformColor, type Provider, type Service } from "@/data/marketplace";
import { formatNumber, localizeData, localizeDuration, pageCopy } from "@/i18n/messages";
import { ArrowUpRight, Check, Clock3, CreditCard, DollarSign, Gauge, RefreshCw, Scale, ShieldCheck, Star, Zap } from "lucide-react";
import { Link } from "wouter";

export function ScoreRing({ score, size = "md", showLabel = false }: { score: number | null; size?: "sm" | "md" | "lg" | "xl"; showLabel?: boolean }) {
  const { locale } = useLocale();
  if (score == null) return <div className="inline-flex flex-col items-center gap-1" aria-label={`${pageCopy[locale].beaconScore}: ${catalogueCopy[locale].insufficient}`} title={catalogueCopy[locale].noScore}><span className="grid size-14 place-items-center rounded-full border-4 border-slate-200 text-xl font-bold text-slate-400">—</span>{showLabel && <span className="max-w-28 text-center text-xs text-slate-500">{catalogueCopy[locale].insufficient}</span>}</div>;
  const radius = size === "xl" ? 54 : size === "lg" ? 40 : size === "sm" ? 18 : 26;
  const strokeWidth = size === "xl" ? 8 : size === "lg" ? 6 : size === "sm" ? 3.5 : 4.5;
  const dimension = (radius + strokeWidth) * 2 + 6;
  const circumference = 2 * Math.PI * radius;
  const offset = circumference - (score / 100) * circumference;
  const badge = score >= 95 ? "Elite" : score >= 90 ? "High" : "Good";
  return <div className="relative inline-flex flex-col items-center justify-center" aria-label={`${pageCopy[locale].beaconScore} ${score}/100`}>
    <div className="relative inline-grid place-items-center" style={{ width: dimension, height: dimension }}><svg viewBox={`0 0 ${dimension} ${dimension}`} className="absolute inset-0 -rotate-90" aria-hidden="true"><circle cx={dimension/2} cy={dimension/2} r={radius} fill="none" stroke="#E2E8F0" strokeWidth={strokeWidth}/><circle cx={dimension/2} cy={dimension/2} r={radius} fill="none" stroke="url(#scoreGradient)" strokeWidth={strokeWidth} strokeLinecap="round" strokeDasharray={circumference} strokeDashoffset={offset}/><defs><linearGradient id="scoreGradient"><stop stopColor="#10B981"/><stop offset=".5" stopColor="#06B6D4"/><stop offset="1" stopColor="#2563EB"/></linearGradient></defs></svg><div className="flex flex-col items-center justify-center leading-none"><bdi className={`${size === "xl" ? "text-3xl" : size === "lg" ? "text-xl" : size === "sm" ? "text-[11px]" : "text-base"} font-black text-slate-900`}>{score}</bdi>{size !== "sm" && <span className="mt-0.5 text-[8px] font-bold uppercase text-slate-400">{pageCopy[locale].score}</span>}</div></div>
    {showLabel && <span className="mt-1 rounded-full bg-emerald-50 px-2 py-0.5 text-[10px] font-bold uppercase text-emerald-700">{localizeData(locale, badge)}</span>}
  </div>;
}

export function VerifiedBadge({ tier, compact = false }: { tier?: string; compact?: boolean }) {
  const { locale } = useLocale();
  const direct = tier?.includes("Direct Source");
  const enterprise = tier?.includes("Enterprise");
  return <span className={`inline-flex items-center gap-1.5 rounded-full font-bold ring-1 ring-inset ${direct ? "bg-emerald-50 text-emerald-800 ring-emerald-200" : enterprise ? "bg-blue-50 text-blue-800 ring-blue-200" : "bg-slate-100 text-slate-800 ring-slate-200"} ${compact ? "px-2 py-0.5 text-[10px]" : "px-3 py-1 text-xs"}`}><ShieldCheck className={compact ? "size-3" : "size-3.5"}/>{compact || !tier ? pageCopy[locale].verified : localizeData(locale, tier)}</span>;
}

export function ApiStatusBadge({ latency, uptime = "—", compact = false }: { latency: string; uptime?: string; compact?: boolean }) {
  const { locale } = useLocale();
  if (latency === "—" || uptime === "—") return <span className="text-xs text-slate-500">{catalogueCopy[locale].unknown}</span>;
  return <div className={`inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white font-medium text-slate-700 ${compact ? "px-2 py-1 text-[11px]" : "px-2.5 py-1.5 text-xs"}`} title={`${localizeData(locale,"Live API Latency")}: ${latency}`}><span className="relative flex size-2"><span className="absolute inline-flex size-2 animate-ping rounded-full bg-emerald-400 opacity-75"/><span className="relative inline-flex size-2 rounded-full bg-emerald-500"/></span><bdi dir="ltr" className="font-semibold text-slate-900">{latency}</bdi><span className="text-slate-400">·</span><bdi dir="ltr" className="text-slate-500">{uptime}</bdi></div>;
}

export function ProviderAvatar({ provider, large = false, xlarge = false }: { provider: Provider; large?: boolean; xlarge?: boolean }) {
  return <div dir="ltr" className={`grid shrink-0 place-items-center rounded-2xl bg-gradient-to-br from-[#0B2A68] via-[#103E99] to-[#0D9488] font-extrabold text-white shadow-md ${xlarge ? "size-20 rounded-3xl text-2xl" : large ? "size-14 text-lg" : "size-11 text-sm"}`}>{provider.initials}</div>;
}

export function PaymentMethodPill({ method }: { method: string }) {
  const lower = method.toLowerCase(); const crypto = lower.includes("crypto") || lower.includes("usdt"); const card = lower.includes("card") || lower.includes("stripe");
  return <span dir="ltr" className={`inline-flex items-center gap-1 rounded-md border px-2 py-0.5 text-[10px] font-semibold ${crypto ? "border-amber-200 bg-amber-50 text-amber-800" : card ? "border-blue-200 bg-blue-50 text-blue-800" : "border-slate-200 bg-slate-100 text-slate-700"}`}>{card ? <CreditCard className="size-2.5"/> : crypto ? <Zap className="size-2.5"/> : null}{method}</span>;
}

export function ProviderCard({ provider, selectedForCompare = false, onToggleCompare, showCompareToggle = true }: { provider: Provider; selectedForCompare?: boolean; onToggleCompare?: (provider: Provider) => void; showCompareToggle?: boolean }) {
  const { locale } = useLocale(); const t = copy[locale]; const p = pageCopy[locale];
  return <article className="group relative flex flex-col justify-between overflow-hidden rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-blue-600 via-teal-500 to-emerald-400"/><div><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><ProviderAvatar provider={provider}/><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Link href={`/providers/${provider.slug}`} className="font-black text-slate-950 hover:text-blue-700">{provider.name}</Link>{provider.verified && <VerifiedBadge tier={provider.tier} compact/>}</div><p className="mt-1 text-xs text-slate-500">{localizeData(locale, provider.location)} · {locale === "ar" ? "مدرج منذ" : "Listed since"} <bdi dir="ltr">{provider.since}</bdi></p></div></div><ScoreRing score={provider.score}/></div><div className="mt-4 flex items-center justify-between border-y border-slate-100 py-2.5"><ApiStatusBadge latency={provider.apiLatency} uptime={provider.apiUptime} compact/><span className="flex items-center gap-1 text-xs font-bold"><Star className="size-3.5 fill-amber-400 text-amber-400"/><bdi dir="ltr">{provider.rating ?? "—"} ({formatNumber(locale, provider.reviews)})</bdi></span></div><div className="mt-3 grid grid-cols-3 divide-x divide-slate-100 rounded-xl bg-slate-50 p-2.5 text-center rtl:divide-x-reverse"><Metric icon={<Gauge/>} value={percentLabel(provider.successRate)} label={p.success}/><Metric icon={<RefreshCw/>} value={localizeData(locale, provider.refillPolicy)} label={p.refill}/><Metric icon={<DollarSign/>} value={provider.minDeposit} label={localizeData(locale,"Min deposit")}/></div><p className="mt-3 line-clamp-2 text-xs leading-5 text-slate-600">{localizeData(locale, provider.description)}</p><div className="mt-3 flex flex-wrap gap-1.5">{provider.paymentMethods.slice(0,3).map(method => <PaymentMethodPill key={method} method={method}/>)}</div></div><div className="mt-5 flex items-center gap-2 border-t border-slate-100 pt-3">{showCompareToggle && onToggleCompare && <button onClick={() => onToggleCompare(provider)} className={`flex items-center gap-1 rounded-xl border px-3 py-2 text-xs font-bold ${selectedForCompare ? "border-cyan-500 bg-cyan-50 text-cyan-800" : "border-slate-200 text-slate-600"}`} title={p.comparison}><Scale className="size-3.5"/>{selectedForCompare ? localizeData(locale,"Added") : t.compare}</button>}<Button variant="outline" asChild className="flex-1 justify-between rounded-xl text-xs font-bold"><Link href={`/providers/${provider.slug}`}>{localizeData(locale,"View Full Profile")}<ArrowUpRight className="size-3.5 rtl:-scale-x-100"/></Link></Button></div></article>;
}

function Metric({icon,value,label}:{icon:React.ReactNode;value:string;label:string}) { return <div className="min-w-0 px-1"><div className="flex items-center justify-center gap-1 text-xs font-black text-slate-900"><span className="[&_svg]:size-3 [&_svg]:text-cyan-600">{icon}</span><bdi dir="ltr" className="truncate">{value}</bdi></div><p className="mt-1 truncate text-[9px] font-bold uppercase text-slate-400">{label}</p></div>; }

export function ProviderTableRow({ provider, selectedForCompare = false, onToggleCompare }: { provider: Provider; selectedForCompare?: boolean; onToggleCompare?: (provider: Provider) => void }) {
  const { locale } = useLocale(); const p = pageCopy[locale];
  return <tr className="border-b border-slate-100 hover:bg-slate-50"><td className="px-4 py-4">{onToggleCompare && <button onClick={() => onToggleCompare(provider)} className={`grid size-5 place-items-center rounded border ${selectedForCompare ? "border-cyan-500 bg-cyan-500 text-white" : "border-slate-300 bg-white"}`} aria-label={`${selectedForCompare ? p.removeFromComparison : p.addToComparison}: ${provider.name}`}>{selectedForCompare && <Check className="size-3.5"/>}</button>}</td><td className="min-w-[240px] px-4 py-4"><Link href={`/providers/${provider.slug}`} className="flex items-center gap-3"><ProviderAvatar provider={provider}/><div><p className="font-extrabold text-slate-950">{provider.name}</p><p className="text-xs text-slate-500">{localizeData(locale,provider.tier)}</p></div></Link></td><td className="px-4 py-4 text-center"><ScoreRing score={provider.score} size="sm"/></td><td className="px-4 py-4"><ApiStatusBadge latency={provider.apiLatency} uptime={provider.apiUptime} compact/></td><td className="px-4 py-4"><bdi dir="ltr" className="font-bold">{percentLabel(provider.successRate)}</bdi><p className="text-[10px] text-slate-400">{localizeData(locale,"Order success")}</p></td><td className="px-4 py-4 text-xs font-bold text-emerald-800">{localizeData(locale,provider.refillPolicy)}</td><td className="px-4 py-4"><bdi dir="ltr" className="font-bold">{provider.minDeposit}</bdi><p className="text-[10px] text-slate-400">{localizeData(locale,"Min deposit")}</p></td><td className="px-4 py-4"><div className="flex gap-1">{provider.paymentMethods.slice(0,2).map(method => <PaymentMethodPill key={method} method={method}/>)}</div></td><td className="px-4 py-4 text-end"><Button asChild size="sm" className="rounded-xl bg-[#0B2A68] text-xs"><Link href={`/providers/${provider.slug}`}>{localizeData(locale,"View Profile")}</Link></Button></td></tr>;
}

export function ServiceRow({ service, selected, onToggle }: { service: Service; selected: boolean; onToggle: (service: Service) => void }) {
  const { providerFor } = useMarketplaceData();
  const provider = providerFor(service); const { locale } = useLocale(); const p = pageCopy[locale];
  return <tr className="service-row"><td className="px-4 py-4"><button onClick={() => onToggle(service)} className={`grid size-5 place-items-center rounded border ${selected ? "border-cyan-500 bg-cyan-500 text-white" : "border-slate-300 bg-white"}`} aria-label={`${selected ? p.removeFromComparison : p.addToComparison}: ${serviceName(locale,service)}`}>{selected && <Check className="size-3.5"/>}</button></td><td className="min-w-[280px] px-4 py-4"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl text-xs font-extrabold text-white" style={{background:platformColor[service.platform]}}>{service.platform.slice(0,2).toUpperCase()}</div><div><p className="font-bold text-slate-900">{serviceName(locale,service)}</p><p className="mt-1 text-xs text-slate-500">{localizeData(locale,service.category)}{!service.billingCycle && <> · {localizeData(locale,service.quality)}</>}</p><OfferEvidence service={service}/></div></div></td><td className="px-4 py-4"><Link href={`/providers/${provider.slug}`} className="flex min-w-[180px] items-center gap-2"><ProviderAvatar provider={provider}/><div><p className="font-semibold text-slate-800">{provider.name}</p><p className="text-xs text-emerald-700">{p.score} <bdi>{provider.score ?? catalogueCopy[locale].insufficient}</bdi></p></div></Link></td><td className="px-4 py-4"><bdi dir="ltr" className="text-lg font-black">{formatPrice(locale, service)}</bdi><p className="text-[10px] text-slate-400">{unitLabel(locale, service)}</p>{service.packageDescription && <p className="mt-1 max-w-xs text-xs text-slate-500" dir="auto">{serviceScope(locale,service)}</p>}{serviceTerms(locale,service) && <p className="mt-2 max-w-xs text-xs leading-5 text-slate-500">{serviceTerms(locale,service)}</p>}</td><td className="px-4 py-4 text-sm"><p className="flex items-center gap-1"><Clock3 className="size-3.5 text-cyan-600"/><bdi dir="ltr">{localizeDuration(locale,service.startTime)}</bdi></p><p className="mt-1 text-xs text-slate-400"><bdi dir="ltr">{localizeDuration(locale,service.delivery)}</bdi></p></td><td className="px-4 py-4"><p className="flex items-center gap-1 text-sm font-semibold"><RefreshCw className="size-3.5 text-blue-600"/>{localizeData(locale,service.refill)}</p><p className="mt-1 text-xs text-slate-400"><bdi dir="ltr">{service.retention == null ? "—" : `${formatNumber(locale,service.retention)}%`}</bdi> {p.retention}</p></td></tr>;
}
